@echo off
echo Input 1 for Newer Wii versions 1.2.0 or older
echo Input 2 for Newer Wii versions 1.3.0 or Newer
SET NWRVER=
SET /P NWRVER=Enter Number and Press Enter:

IF %NWRVER%==1 GOTO LH
IF %NWRVER%==2 GOTO LZ


:LH
ntcompress Stages/01-01.arc.LH -x -o Stages/01-01.arc
ntcompress Stages/01-02.arc.LH -x -o Stages/01-02.arc
ntcompress Stages/01-03.arc.LH -x -o Stages/01-03.arc
ntcompress Stages/01-04.arc.LH -x -o Stages/01-04.arc
ntcompress Stages/01-05.arc.LH -x -o Stages/01-05.arc 
ntcompress Stages/01-06.arc.LH -x -o Stages/01-06.arc 
ntcompress Stages/01-07.arc.LH -x -o Stages/01-07.arc 
ntcompress Stages/01-08.arc.LH -x -o Stages/01-08.arc 
ntcompress Stages/01-09.arc.LH -x -o Stages/01-09.arc 
ntcompress Stages/01-10.arc.LH -x -o Stages/01-10.arc 
ntcompress Stages/01-11.arc.LH -x -o Stages/01-11.arc 
ntcompress Stages/01-12.arc.LH -x -o Stages/01-12.arc 
ntcompress Stages/01-13.arc.LH -x -o Stages/01-13.arc 
ntcompress Stages/01-14.arc.LH -x -o Stages/01-14.arc 
ntcompress Stages/01-15.arc.LH -x -o Stages/01-15.arc 
ntcompress Stages/01-25.arc.LH -x -o Stages/01-25.arc 
ntcompress Stages/01-31.arc.LH -x -o Stages/01-31.arc 
ntcompress Stages/01-33.arc.LH -x -o Stages/01-33.arc
ntcompress Stages/01-34.arc.LH -x -o Stages/01-34.arc
ntcompress Stages/01-38.arc.LH -x -o Stages/01-38.arc
ntcompress Stages/01-40.arc.LH -x -o Stages/01-40.arc 
ntcompress Stages/01-41.arc.LH -x -o Stages/01-41.arc 
ntcompress Stages/01-42.arc.LH -x -o Stages/01-42.arc 
ntcompress Stages/01-99.arc.LH -x -o Stages/01-99.arc 
ntcompress Stages/02-01.arc.LH -x -o Stages/02-01.arc
ntcompress Stages/02-02.arc.LH -x -o Stages/02-02.arc
ntcompress Stages/02-03.arc.LH -x -o Stages/02-03.arc
ntcompress Stages/02-04.arc.LH -x -o Stages/02-04.arc
ntcompress Stages/02-05.arc.LH -x -o Stages/02-05.arc
ntcompress Stages/02-06.arc.LH -x -o Stages/02-06.arc
ntcompress Stages/02-07.arc.LH -x -o Stages/02-07.arc
ntcompress Stages/02-08.arc.LH -x -o Stages/02-08.arc
ntcompress Stages/02-09.arc.LH -x -o Stages/02-09.arc
ntcompress Stages/02-10.arc.LH -x -o Stages/02-10.arc
ntcompress Stages/02-11.arc.LH -x -o Stages/02-11.arc
ntcompress Stages/02-12.arc.LH -x -o Stages/02-12.arc
ntcompress Stages/02-13.arc.LH -x -o Stages/02-13.arc
ntcompress Stages/02-14.arc.LH -x -o Stages/02-14.arc
ntcompress Stages/02-15.arc.LH -x -o Stages/02-15.arc
ntcompress Stages/02-25.arc.LH -x -o Stages/02-25.arc
ntcompress Stages/02-33.arc.LH -x -o Stages/02-33.arc
ntcompress Stages/02-34.arc.LH -x -o Stages/02-34.arc
ntcompress Stages/02-38.arc.LH -x -o Stages/02-38.arc
ntcompress Stages/02-41.arc.LH -x -o Stages/02-41.arc
ntcompress Stages/02-99.arc.LH -x -o Stages/02-99.arc
ntcompress Stages/03-01.arc.LH -x -o Stages/03-01.arc
ntcompress Stages/03-02.arc.LH -x -o Stages/03-02.arc
ntcompress Stages/03-04.arc.LH -x -o Stages/03-04.arc
ntcompress Stages/03-03.arc.LH -x -o Stages/03-03.arc
ntcompress Stages/03-05.arc.LH -x -o Stages/03-05.arc
ntcompress Stages/03-06.arc.LH -x -o Stages/03-06.arc
ntcompress Stages/03-07.arc.LH -x -o Stages/03-07.arc
ntcompress Stages/03-09.arc.LH -x -o Stages/03-09.arc
ntcompress Stages/03-08.arc.LH -x -o Stages/03-08.arc
ntcompress Stages/03-10.arc.LH -x -o Stages/03-10.arc
ntcompress Stages/03-11.arc.LH -x -o Stages/03-11.arc
ntcompress Stages/03-12.arc.LH -x -o Stages/03-12.arc
ntcompress Stages/03-14.arc.LH -x -o Stages/03-14.arc
ntcompress Stages/03-13.arc.LH -x -o Stages/03-13.arc
ntcompress Stages/03-25.arc.LH -x -o Stages/03-25.arc
ntcompress Stages/03-15.arc.LH -x -o Stages/03-15.arc
ntcompress Stages/03-33.arc.LH -x -o Stages/03-33.arc
ntcompress Stages/03-34.arc.LH -x -o Stages/03-34.arc
ntcompress Stages/03-38.arc.LH -x -o Stages/03-38.arc
ntcompress Stages/03-99.arc.LH -x -o Stages/03-99.arc
ntcompress Stages/04-01.arc.LH -x -o Stages/04-01.arc
ntcompress Stages/04-02.arc.LH -x -o Stages/04-02.arc
ntcompress Stages/04-03.arc.LH -x -o Stages/04-03.arc
ntcompress Stages/04-04.arc.LH -x -o Stages/04-04.arc
ntcompress Stages/04-05.arc.LH -x -o Stages/04-05.arc
ntcompress Stages/04-06.arc.LH -x -o Stages/04-06.arc
ntcompress Stages/04-07.arc.LH -x -o Stages/04-07.arc
ntcompress Stages/04-08.arc.LH -x -o Stages/04-08.arc
ntcompress Stages/04-09.arc.LH -x -o Stages/04-09.arc
ntcompress Stages/04-10.arc.LH -x -o Stages/04-10.arc
ntcompress Stages/04-11.arc.LH -x -o Stages/04-11.arc
ntcompress Stages/04-12.arc.LH -x -o Stages/04-12.arc
ntcompress Stages/04-15.arc.LH -x -o Stages/04-15.arc
ntcompress Stages/04-25.arc.LH -x -o Stages/04-25.arc
ntcompress Stages/04-31.arc.LH -x -o Stages/04-31.arc
ntcompress Stages/04-33.arc.LH -x -o Stages/04-33.arc
ntcompress Stages/04-34.arc.LH -x -o Stages/04-34.arc
ntcompress Stages/04-38.arc.LH -x -o Stages/04-38.arc
ntcompress Stages/04-99.arc.LH -x -o Stages/04-99.arc
ntcompress Stages/05-01.arc.LH -x -o Stages/05-01.arc
ntcompress Stages/05-02.arc.LH -x -o Stages/05-02.arc
ntcompress Stages/05-03.arc.LH -x -o Stages/05-03.arc
ntcompress Stages/05-04.arc.LH -x -o Stages/05-04.arc
ntcompress Stages/05-05.arc.LH -x -o Stages/05-05.arc
ntcompress Stages/05-06.arc.LH -x -o Stages/05-06.arc
ntcompress Stages/05-07.arc.LH -x -o Stages/05-07.arc
ntcompress Stages/05-08.arc.LH -x -o Stages/05-08.arc
ntcompress Stages/05-09.arc.LH -x -o Stages/05-09.arc
ntcompress Stages/05-10.arc.LH -x -o Stages/05-10.arc
ntcompress Stages/05-11.arc.LH -x -o Stages/05-11.arc
ntcompress Stages/05-15.arc.LH -x -o Stages/05-15.arc
ntcompress Stages/05-25.arc.LH -x -o Stages/05-25.arc
ntcompress Stages/05-33.arc.LH -x -o Stages/05-33.arc
ntcompress Stages/05-34.arc.LH -x -o Stages/05-34.arc
ntcompress Stages/05-99.arc.LH -x -o Stages/05-99.arc
ntcompress Stages/05-38.arc.LH -x -o Stages/05-38.arc
ntcompress Stages/06-01.arc.LH -x -o Stages/06-01.arc
ntcompress Stages/06-02.arc.LH -x -o Stages/06-02.arc
ntcompress Stages/06-03.arc.LH -x -o Stages/06-03.arc
ntcompress Stages/06-04.arc.LH -x -o Stages/06-04.arc
ntcompress Stages/06-05.arc.LH -x -o Stages/06-05.arc
ntcompress Stages/06-06.arc.LH -x -o Stages/06-06.arc
ntcompress Stages/06-07.arc.LH -x -o Stages/06-07.arc
ntcompress Stages/06-08.arc.LH -x -o Stages/06-08.arc
ntcompress Stages/06-09.arc.LH -x -o Stages/06-09.arc
ntcompress Stages/06-15.arc.LH -x -o Stages/06-15.arc
ntcompress Stages/06-24.arc.LH -x -o Stages/06-24.arc 
ntcompress Stages/06-25.arc.LH -x -o Stages/06-25.arc
ntcompress Stages/06-33.arc.LH -x -o Stages/06-33.arc
ntcompress Stages/06-34.arc.LH -x -o Stages/06-34.arc
ntcompress Stages/06-38.arc.LH -x -o Stages/06-38.arc
ntcompress Stages/06-99.arc.LH -x -o Stages/06-99.arc
ntcompress Stages/07-01.arc.LH -x -o Stages/07-01.arc
ntcompress Stages/07-02.arc.LH -x -o Stages/07-02.arc
ntcompress Stages/07-03.arc.LH -x -o Stages/07-03.arc
ntcompress Stages/07-05.arc.LH -x -o Stages/07-05.arc
ntcompress Stages/07-06.arc.LH -x -o Stages/07-06.arc
ntcompress Stages/07-07.arc.LH -x -o Stages/07-07.arc
ntcompress Stages/07-04.arc.LH -x -o Stages/07-04.arc
ntcompress Stages/07-08.arc.LH -x -o Stages/07-08.arc
ntcompress Stages/07-15.arc.LH -x -o Stages/07-15.arc
ntcompress Stages/07-25.arc.LH -x -o Stages/07-25.arc
ntcompress Stages/07-31.arc.LH -x -o Stages/07-31.arc
ntcompress Stages/07-33.arc.LH -x -o Stages/07-33.arc
ntcompress Stages/07-34.arc.LH -x -o Stages/07-34.arc
ntcompress Stages/07-38.arc.LH -x -o Stages/07-38.arc
ntcompress Stages/07-41.arc.LH -x -o Stages/07-41.arc
ntcompress Stages/07-99.arc.LH -x -o Stages/07-99.arc
ntcompress Stages/08-01.arc.LH -x -o Stages/08-01.arc
ntcompress Stages/08-02.arc.LH -x -o Stages/08-02.arc
ntcompress Stages/08-03.arc.LH -x -o Stages/08-03.arc
ntcompress Stages/08-04.arc.LH -x -o Stages/08-04.arc
ntcompress Stages/08-05.arc.LH -x -o Stages/08-05.arc
ntcompress Stages/08-06.arc.LH -x -o Stages/08-06.arc
ntcompress Stages/08-07.arc.LH -x -o Stages/08-07.arc
ntcompress Stages/08-08.arc.LH -x -o Stages/08-08.arc
ntcompress Stages/08-09.arc.LH -x -o Stages/08-09.arc
ntcompress Stages/08-10.arc.LH -x -o Stages/08-10.arc
ntcompress Stages/08-15.arc.LH -x -o Stages/08-15.arc
ntcompress Stages/08-16.arc.LH -x -o Stages/08-16.arc
ntcompress Stages/08-24.arc.LH -x -o Stages/08-24.arc
ntcompress Stages/08-25.arc.LH -x -o Stages/08-25.arc
ntcompress Stages/08-26.arc.LH -x -o Stages/08-26.arc
ntcompress Stages/08-27.arc.LH -x -o Stages/08-27.arc
ntcompress Stages/08-28.arc.LH -x -o Stages/08-28.arc
ntcompress Stages/08-29.arc.LH -x -o Stages/08-29.arc
ntcompress Stages/08-30.arc.LH -x -o Stages/08-30.arc
ntcompress Stages/08-31.arc.LH -x -o Stages/08-31.arc
ntcompress Stages/08-33.arc.LH -x -o Stages/08-33.arc
ntcompress Stages/08-34.arc.LH -x -o Stages/08-34.arc
ntcompress Stages/08-41.arc.LH -x -o Stages/08-41.arc
ntcompress Stages/08-42.arc.LH -x -o Stages/08-42.arc
ntcompress Stages/08-99.arc.LH -x -o Stages/08-99.arc
ntcompress Stages/09-01.arc.LH -x -o Stages/09-01.arc
ntcompress Stages/09-02.arc.LH -x -o Stages/09-02.arc
ntcompress Stages/09-03.arc.LH -x -o Stages/09-03.arc
ntcompress Stages/09-04.arc.LH -x -o Stages/09-04.arc
ntcompress Stages/09-05.arc.LH -x -o Stages/09-05.arc
ntcompress Stages/09-06.arc.LH -x -o Stages/09-06.arc
ntcompress Stages/09-07.arc.LH -x -o Stages/09-07.arc
ntcompress Stages/09-08.arc.LH -x -o Stages/09-08.arc
ntcompress Stages/09-09.arc.LH -x -o Stages/09-09.arc
ntcompress Stages/09-10.arc.LH -x -o Stages/09-10.arc
ntcompress Stages/09-11.arc.LH -x -o Stages/09-11.arc
ntcompress Stages/09-12.arc.LH -x -o Stages/09-12.arc
ntcompress Stages/09-13.arc.LH -x -o Stages/09-13.arc
ntcompress Stages/09-14.arc.LH -x -o Stages/09-14.arc
ntcompress Stages/09-16.arc.LH -x -o Stages/09-16.arc
ntcompress Stages/09-17.arc.LH -x -o Stages/09-17.arc
ntcompress Stages/09-18.arc.LH -x -o Stages/09-18.arc
ntcompress Stages/09-19.arc.LH -x -o Stages/09-19.arc
ntcompress Stages/09-22.arc.LH -x -o Stages/09-22.arc
ntcompress Stages/09-25.arc.LH -x -o Stages/09-25.arc
ntcompress Stages/09-33.arc.LH -x -o Stages/09-33.arc
ntcompress Stages/09-34.arc.LH -x -o Stages/09-34.arc
ntcompress Stages/09-35.arc.LH -x -o Stages/09-35.arc
ntcompress Stages/09-36.arc.LH -x -o Stages/09-36.arc
ntcompress Stages/09-99.arc.LH -x -o Stages/09-99.arc
ntcompress Stages/10-01.arc.LH -x -o Stages/10-01.arc
ntcompress Stages/10-02.arc.LH -x -o Stages/10-02.arc
ntcompress Stages/10-03.arc.LH -x -o Stages/10-03.arc
ntcompress Stages/10-04.arc.LH -x -o Stages/10-04.arc
ntcompress Stages/10-05.arc.LH -x -o Stages/10-05.arc
ntcompress Stages/10-06.arc.LH -x -o Stages/10-06.arc
ntcompress Stages/10-07.arc.LH -x -o Stages/10-07.arc
ntcompress Stages/10-08.arc.LH -x -o Stages/10-08.arc
ntcompress Stages/10-09.arc.LH -x -o Stages/10-09.arc
ntcompress Stages/10-10.arc.LH -x -o Stages/10-10.arc
ntcompress Stages/10-11.arc.LH -x -o Stages/10-11.arc
ntcompress Stages/10-12.arc.LH -x -o Stages/10-12.arc
ntcompress Stages/10-13.arc.LH -x -o Stages/10-13.arc
ntcompress Stages/10-14.arc.LH -x -o Stages/10-14.arc
ntcompress Stages/10-15.arc.LH -x -o Stages/10-15.arc
ntcompress Stages/10-16.arc.LH -x -o Stages/10-16.arc
ntcompress Stages/10-17.arc.LH -x -o Stages/10-17.arc
ntcompress Stages/10-18.arc.LH -x -o Stages/10-18.arc
ntcompress Stages/10-19.arc.LH -x -o Stages/10-19.arc
ntcompress Stages/10-20.arc.LH -x -o Stages/10-20.arc
ntcompress Stages/10-22.arc.LH -x -o Stages/10-22.arc
ntcompress Stages/10-23.arc.LH -x -o Stages/10-23.arc
ntcompress Stages/10-24.arc.LH -x -o Stages/10-24.arc
ntcompress Stages/10-25.arc.LH -x -o Stages/10-25.arc
ntcompress Stages/10-31.arc.LH -x -o Stages/10-31.arc
ntcompress Stages/10-33.arc.LH -x -o Stages/10-33.arc
ntcompress Stages/10-34.arc.LH -x -o Stages/10-34.arc
ntcompress Stages/10-35.arc.LH -x -o Stages/10-35.arc
ntcompress Stages/10-36.arc.LH -x -o Stages/10-36.arc
ntcompress Stages/10-37.arc.LH -x -o Stages/10-37.arc
ntcompress Stages/10-99.arc.LH -x -o Stages/10-99.arc
ntcompress Layouts/classic.arc.LH -x -o Layouts/classic.arc
ntcompress Layouts/coin.arc.LH -x -o Layouts/coin.arc
ntcompress Layouts/corseClear.arc.LH -x -o Layouts/corseClear.arc
ntcompress Layouts/MapHUD.arc.LH -x -o Layouts/MapHUD.arc
ntcompress Layouts/msgbox.arc.LH -x -o Layouts/msgbox.arc
ntcompress Layouts/shop.arc.LH -x -o Layouts/shop.arc
ntcompress Layouts/StarCoins.arc.LH -x -o Layouts/StarCoins.arc
ntcompress BGs/bgA_0B02.arc.LH -x -o BGs/bgA_0B02.arc
ntcompress BGs/bgA_0C03.arc.LH -x -o BGs/bgA_0C03.arc
ntcompress BGs/bgA_3DC2.arc.LH -x -o BGs/bgA_3DC2.arc
ntcompress BGs/bgA_3F03.arc.LH -x -o BGs/bgA_3F03.arc
ntcompress BGs/bgA_3FE2.arc.LH -x -o BGs/bgA_3FE2.arc
ntcompress BGs/bgA_3FF2.arc.LH -x -o BGs/bgA_3FF2.arc
ntcompress BGs/bgA_1003.arc.LH -x -o BGs/bgA_1003.arc
ntcompress BGs/bgA_9986.arc.LH -x -o BGs/bgA_9986.arc
ntcompress BGs/bgA_9989.arc.LH -x -o BGs/bgA_9989.arc
ntcompress BGs/bgA_9990.arc.LH -x -o BGs/bgA_9990.arc
ntcompress BGs/bgA_9995.arc.LH -x -o BGs/bgA_9995.arc
ntcompress BGs/bgA_9998.arc.LH -x -o BGs/bgA_9998.arc
ntcompress BGs/bgA_A602.arc.LH -x -o BGs/bgA_A602.arc
ntcompress BGs/bgA_B602.arc.LH -x -o BGs/bgA_B602.arc
ntcompress BGs/bgA_CCC1.arc.LH -x -o BGs/bgA_CCC1.arc
ntcompress BGs/bgA_EFEF.arc.LH -x -o BGs/bgA_EFEF.arc
ntcompress BGs/bgA_F1F2.arc.LH -x -o BGs/bgA_F1F2.arc
ntcompress BGs/bgA_F949.arc.LH -x -o BGs/bgA_F949.arc
ntcompress BGs/bgB_0CA2.arc.LH -x -o BGs/bgB_0CA2.arc
ntcompress BGs/bgB_3FE2.arc.LH -x -o BGs/bgB_3FE2.arc
ntcompress BGs/bgB_3FF2.arc.LH -x -o BGs/bgB_3FF2.arc
ntcompress BGs/bgB_43A2.arc.LH -x -o BGs/bgB_43A2.arc
ntcompress BGs/bgB_52AA.arc.LH -x -o BGs/bgB_52AA.arc
ntcompress BGs/bgB_1003.arc.LH -x -o BGs/bgB_1003.arc
ntcompress BGs/bgB_5212.arc.LH -x -o BGs/bgB_5212.arc
ntcompress BGs/bgB_6000.arc.LH -x -o BGs/bgB_6000.arc
ntcompress BGs/bgB_6001.arc.LH -x -o BGs/bgB_6001.arc
ntcompress BGs/bgB_6005.arc.LH -x -o BGs/bgB_6005.arc
ntcompress BGs/bgB_6006.arc.LH -x -o BGs/bgB_6006.arc
ntcompress BGs/bgB_7003.arc.LH -x -o BGs/bgB_7003.arc
ntcompress BGs/bgB_9000.arc.LH -x -o BGs/bgB_9000.arc
ntcompress BGs/bgB_9002.arc.LH -x -o BGs/bgB_9002.arc
ntcompress BGs/bgB_9003.arc.LH -x -o BGs/bgB_9003.arc
ntcompress BGs/bgB_9004.arc.LH -x -o BGs/bgB_9004.arc
ntcompress BGs/bgB_9008.arc.LH -x -o BGs/bgB_9008.arc
ntcompress BGs/bgB_9009.arc.LH -x -o BGs/bgB_9009.arc
ntcompress BGs/bgB_9010.arc.LH -x -o BGs/bgB_9010.arc
ntcompress BGs/bgB_9011.arc.LH -x -o BGs/bgB_9011.arc
ntcompress BGs/bgB_9198.arc.LH -x -o BGs/bgB_9198.arc
ntcompress BGs/bgB_9986.arc.LH -x -o BGs/bgB_9986.arc
ntcompress BGs/bgB_9987.arc.LH -x -o BGs/bgB_9987.arc
ntcompress BGs/bgB_9988.arc.LH -x -o BGs/bgB_9988.arc
ntcompress BGs/bgB_9989.arc.LH -x -o BGs/bgB_9989.arc
ntcompress BGs/bgB_9991.arc.LH -x -o BGs/bgB_9991.arc
ntcompress BGs/bgB_9997.arc.LH -x -o BGs/bgB_9997.arc
ntcompress BGs/bgB_9999.arc.LH -x -o BGs/bgB_9999.arc
ntcompress BGs/bgB_A474.arc.LH -x -o BGs/bgB_A474.arc
ntcompress BGs/bgB_A602.arc.LH -x -o BGs/bgB_A602.arc
ntcompress BGs/bgB_AA02.arc.LH -x -o BGs/bgB_AA02.arc
ntcompress BGs/bgB_ABCD.arc.LH -x -o BGs/bgB_ABCD.arc
ntcompress BGs/bgB_B00B.arc.LH -x -o BGs/bgB_B00B.arc
ntcompress BGs/bgB_B6B2.arc.LH -x -o BGs/bgB_B6B2.arc
ntcompress BGs/bgB_B602.arc.LH -x -o BGs/bgB_B602.arc
ntcompress BGs/bgB_C02C.arc.LH -x -o BGs/bgB_C02C.arc
ntcompress BGs/bgB_C02E.arc.LH -x -o BGs/bgB_C02E.arc
ntcompress BGs/bgB_C415.arc.LH -x -o BGs/bgB_C415.arc
ntcompress BGs/bgB_CA22.arc.LH -x -o BGs/bgB_CA22.arc
ntcompress BGs/bgB_F1F2.arc.LH -x -o BGs/bgB_F1F2.arc
ntcompress BGs/bgB_FAE2.arc.LH -x -o BGs/bgB_FAE2.arc
ntcompress BGs/bgB_FAF2.arc.LH -x -o BGs/bgB_FAF2.arc
ntcompress BGs/bgB_FCB2.arc.LH -x -o BGs/bgB_FCB2.arc
ntcompress Maps/Bonus.kpbin.LH -x -o Maps/Bonus.kpbin
ntcompress Maps/CrystalCaverns.kpbin.LH -x -o  Maps/CrystalCaverns.kpbin
ntcompress Maps/Cutland.kpbin.LH -x -o Maps/Cutland.kpbin
ntcompress Maps/Flamesinside.kpbin.LH -x -o Maps/Flamesinside.kpbin
ntcompress Maps/Fullmap.kpbin.LH -x -o Maps/Fullmap.kpbin
ntcompress Maps/Goldwood.kpbin.LH -x -o Maps/Goldwood.kpbin
ntcompress Maps/KoopaPlanet.kpbin.LH -x -o Maps/KoopaPlanet.kpbin
ntcompress Maps/KoopaPlanetUnd.kpbin.LH -x -o Maps/KoopaPlanetUnd.kpbin
ntcompress Maps/Lava.brres.LH -x -o Maps/Lava.brres
ntcompress Maps/Minimega.kpbin.LH -x -o Maps/Minimega.kpbin
ntcompress Maps/MountainBackside.kpbin.LH -x -o Maps/MountainBackside.kpbin
ntcompress Maps/Sewer.kpbin.LH -x -o  Maps/Sewer.kpbin
ntcompress Maps/SI_Hammer.arc.LH -x -o Maps/SI_Hammer.arc
ntcompress Maps/SkyCity.kpbin.LH -x -o Maps/SkyCity.kpbin
ntcompress Maps/StarrySky.kpbin.LH -x -o Maps/StarrySky.kpbin
ntcompress Maps/Water.brres.LH -x -o Maps/Water.brres
ntcompress Maps/WSEL.kpbin.LH -x -o Maps/WSEL.kpbin
ntcompress Maps/YoshiIsland.kpbin.LH -x -o Maps/YoshiIsland.kpbin
ntcompress Maps/Texture/Beach.bin.LH -x -o Maps/Texture/Beach.bin
ntcompress Maps/Texture/Beach2.bin.LH -x -o Maps/Texture/Beach2.bin
ntcompress Maps/Texture/Beach3.bin.LH -x -o Maps/Texture/Beach3.bin
ntcompress Maps/Texture/Beach4.bin.LH -x -o Maps/Texture/Beach4.bin
ntcompress Maps/Texture/Beach4_RGBA8.bin.LH -x -o Maps/Texture/Beach4_RGBA8.bin
ntcompress Maps/Texture/Beach5.bin.LH -x -o Maps/Texture/Beach5.bin
ntcompress Maps/Texture/Bonus.bin.LH -x -o Maps/Texture/Bonus.bin
ntcompress Maps/Texture/Cavern.bin.LH -x -o Maps/Texture/Cavern.bin
ntcompress Maps/Texture/CavernsDark.bin.LH -x -o Maps/Texture/CavernsDark.bin
ntcompress Maps/Texture/CRYSTALCAVE.bin.LH -x -o Maps/Texture/CRYSTALCAVE.bin
ntcompress Maps/Texture/DARKCRYSTALCAVE.bin.LH -x -o  Maps/Texture/DARKCRYSTALCAVE.bin
ntcompress Maps/Texture/DarkLavaGlow.bin.LH -x -o Maps/Texture/DarkLavaGlow.bin
ntcompress Maps/Texture/Desert.bin.LH -x -o Maps/Texture/Desert.bin
ntcompress Maps/Texture/Flagstones.bin.LH -x -o Maps/Texture/Flagstones.bin
ntcompress Maps/Texture/Forest.bin.LH -x -o Maps/Texture/Forest.bin
ntcompress Maps/Texture/Forest2.bin.LH -x -o Maps/Texture/Forest2.bin
ntcompress Maps/Texture/Ghostland.bin.LH -x -o Maps/Texture/Ghostland.bin
ntcompress Maps/Texture/Goldwood.bin.LH -x -o Maps/Texture/Goldwood.bin
ntcompress Maps/Texture/JungleRuins.bin.LH -x -o Maps/Texture/JungleRuins.bin
ntcompress Maps/Texture/KoopaOUT1.bin.LH -x -o Maps/Texture/KoopaOUT1.bin
ntcompress Maps/Texture/KoopaOUT2.bin.LH -x -o Maps/Texture/KoopaOUT2.bin
ntcompress Maps/Texture/LavaGlow.bin.LH -x -o Maps/Texture/LavaGlow.bin
ntcompress Maps/Texture/MiniMega.bin.LH -x -o Maps/Texture/MiniMega.bin
ntcompress Maps/Texture/MtMush.bin.LH -x -o Maps/Texture/MtMush.bin
ntcompress Maps/Texture/NewBeach_RGBA8.bin.LH -x -o Maps/Texture/NewBeach_RGBA8.bin
ntcompress Maps/Texture/NoharaN.bin.LH -x -o Maps/Texture/NoharaN.bin
ntcompress Maps/Texture/Paths_W1.bin.LH -x -o Maps/Texture/Paths_W1.bin
ntcompress Maps/Texture/Paths_W2.bin.LH -x -o Maps/Texture/Paths_W2.bin
ntcompress Maps/Texture/Paths_W3.bin.LH -x -o Maps/Texture/Paths_W3.bin
ntcompress Maps/Texture/Paths_W4.bin.LH -x -o Maps/Texture/Paths_W4.bin
ntcompress Maps/Texture/Paths_W5.bin.LH -x -o Maps/Texture/Paths_W5.bin
ntcompress Maps/Texture/Paths_W6.bin.LH -x -o Maps/Texture/Paths_W6.bin
ntcompress Maps/Texture/Paths_W7.bin.LH -x -o Maps/Texture/Paths_W7.bin
ntcompress Maps/Texture/Paths_W8.bin.LH -x -o Maps/Texture/Paths_W8.bin
ntcompress Maps/Texture/Pumpkin.bin.LH -x -o Maps/Texture/Pumpkin.bin
ntcompress Maps/Texture/PumpkinSpecial.bin.LH -x -o Maps/Texture/PumpkinSpecial.bin
ntcompress Maps/Texture/RisingSun.bin.LH -x -o Maps/Texture/RisingSun.bin
ntcompress Maps/Texture/Rocky.bin.LH -x -o Maps/Texture/Rocky.bin
ntcompress Maps/Texture/Sand.bin.LH -x -o Maps/Texture/Sand.bin
ntcompress Maps/Texture/Snowinside1.bin.LH -x -o Maps/Texture/Snowinside1.bin
ntcompress Maps/Texture/Snowinside1_lavay.bin.LH -x -o Maps/Texture/Snowinside1_lavay.bin
ntcompress Maps/Texture/Snowinside2.bin.LH -x -o Maps/Texture/Snowinside2.bin
ntcompress Maps/Texture/Snowinside3.bin.LH -x -o Maps/Texture/Snowinside3.bin
ntcompress Maps/Texture/Snowinside2_lavay.bin.LH -x -o Maps/Texture/Snowinside2_lavay.bin
ntcompress Maps/Texture/Snowinside3_lavay.bin.LH -x -o Maps/Texture/Snowinside3_lavay.bin
ntcompress Maps/Texture/Snowoutside.bin.LH -x -o Maps/Texture/Snowoutside.bin
ntcompress Maps/Texture/StarHaven.bin.LH -x -o Maps/Texture/StarHaven.bin
ntcompress Maps/Texture/StarHavenUpDown.bin.LH -x -o Maps/Texture/StarHavenUpDown.bin
ntcompress Maps/Texture/StarRoad.bin.LH -x -o Maps/Texture/StarRoad.bin
ntcompress Maps/Texture/uPaths_W1.bin.LH -x -o Maps/Texture/uPaths_W1.bin
ntcompress Maps/Texture/W1Paths.bin.LH -x -o Maps/Texture/W1Paths.bin
ntcompress "Maps/Texture/Water Edge Fullmap.bin.LH" -x -o "Maps/Texture/Water Edge Fullmap.bin"
ntcompress Maps/Texture/Water-Edge--FF-SAK.bin.LH -x -o Maps/Texture/Water-Edge--FF-SAK.bin
ntcompress Maps/Texture/Water-Edge--MM,-GW.bin.LH -x -o Maps/Texture/Water-Edge--MM,-GW.bin
ntcompress Maps/Texture/Water-Edge--SW,-CC.bin.LH -x -o Maps/Texture/Water-Edge--SW,-CC.bin
ntcompress Maps/Texture/WCCPaths.bin.LH -x -o Maps/Texture/WCCPaths.bin
ntcompress Maps/Texture/wsele.bin.LH -x -o Maps/Texture/wsele.bin
ntcompress SpriteTex/arrow.arc.LH -x -o SpriteTex/arrow.arc
ntcompress SpriteTex/big_renga_block.arc.LH -x -o SpriteTex/big_renga_block.arc
ntcompress SpriteTex/big_shell.arc.LH -x -o SpriteTex/big_shell.arc
ntcompress SpriteTex/block_arrow.arc.LH -x -o SpriteTex/block_arrow.arc
ntcompress SpriteTex/block_jump.arc.LH -x -o SpriteTex/block_jump.arc
ntcompress SpriteTex/block_light.arc.LH -x -o SpriteTex/block_light.arc
ntcompress SpriteTex/block_rotate.arc.LH -x -o SpriteTex/block_rotate.arc
ntcompress SpriteTex/block_slide.arc.LH -x -o SpriteTex/block_slide.arc
ntcompress SpriteTex/bombhei.arc.LH -x -o SpriteTex/bombhei.arc
ntcompress SpriteTex/boss_koopa_lift_down.arc.LH -x -o SpriteTex/boss_koopa_lift_down.arc
ntcompress SpriteTex/bros.arc.LH -x -o SpriteTex/bros.arc
ntcompress SpriteTex/bubble.arc.LH -x -o SpriteTex/bubble.arc
ntcompress SpriteTex/cage_boss_koopa.arc.LH -x -o SpriteTex/cage_boss_koopa.arc
ntcompress SpriteTex/chestnut.arc.LH -x -o SpriteTex/chestnut.arc
ntcompress SpriteTex/choropoo.arc.LH -x -o SpriteTex/choropoo.arc
ntcompress SpriteTex/circle_ground.arc.LH -x -o SpriteTex/circle_ground.arc
ntcompress SpriteTex/circle_ground_chika.arc.LH -x -o SpriteTex/circle_ground_chika.arc
ntcompress SpriteTex/circle_ground_koopa.arc.LH -x -o SpriteTex/circle_ground_koopa.arc
ntcompress SpriteTex/cobCourse.arc.LH -x -o SpriteTex/cobCourse.arc
ntcompress SpriteTex/CreditsBG.arc.LH -x -o SpriteTex/CreditsBG.arc
ntcompress SpriteTex/dossun.arc.LH -x -o SpriteTex/dossun.arc
ntcompress SpriteTex/env_leaf.arc.LH -x -o SpriteTex/env_leaf.arc
ntcompress SpriteTex/env_petal.arc.LH -x -o SpriteTex/env_petal.arc
ntcompress SpriteTex/env_stardust.arc.LH -x -o SpriteTex/env_stardust.arc
ntcompress SpriteTex/fire_cannon.arc.LH -x -o SpriteTex/fire_cannon.arc
ntcompress SpriteTex/fruit_cookie.arc.LH -x -o SpriteTex/fruit_cookie.arc
ntcompress SpriteTex/fruits_kusa.arc.LH -x -o SpriteTex/fruits_kusa.arc
ntcompress SpriteTex/gabon.arc.LH -x -o SpriteTex/gabon.arc
ntcompress SpriteTex/gabon_rock.arc.LH -x -o SpriteTex/gabon_rock.arc
ntcompress SpriteTex/goal_set.arc.LH -x -o SpriteTex/goal_set.arc
ntcompress SpriteTex/I_hammer.arc.LH -x -o SpriteTex/I_hammer.arc
ntcompress SpriteTex/hammerM.arc.LH -x -o SpriteTex/hammerM.arc
ntcompress SpriteTex/I_kinoko_bundle.arc.LH -x -o SpriteTex/I_kinoko_bundle.arc
ntcompress SpriteTex/I_star.arc.LH -x -o SpriteTex/I_star.arc
ntcompress SpriteTex/I_yoshi_egg.arc.LH -x -o SpriteTex/I_yoshi_egg.arc
ntcompress SpriteTex/ibaramushi.arc.LH -x -o SpriteTex/ibaramushi.arc
ntcompress SpriteTex/iron_ball.arc.LH -x -o SpriteTex/iron_ball.arc
ntcompress SpriteTex/kameck_princess.arc.LH -x -o SpriteTex/kameck_princess.arc
ntcompress SpriteTex/kanibo.arc.LH -x -o SpriteTex/kanibo.arc
ntcompress SpriteTex/Kinopio.arc.LH -x -o SpriteTex/Kinopio.arc
ntcompress SpriteTex/koopa.arc.LH -x -o SpriteTex/koopa.arc
ntcompress SpriteTex/koopaJr_clown_ply.arc.LH -x -o SpriteTex/koopaJr_clown_ply.arc
ntcompress SpriteTex/KoopaShip.arc.LH -x -o SpriteTex/KoopaShip.arc
ntcompress SpriteTex/kuribo.arc.LH -x -o SpriteTex/kuribo.arc
ntcompress SpriteTex/kuriboBig.arc.LH -x -o SpriteTex/kuriboBig.arc
ntcompress SpriteTex/kuriboBoss.arc.LH -x -o SpriteTex/kuriboBoss.arc
ntcompress SpriteTex/lakitu.arc.LH -x -o SpriteTex/lakitu.arc
ntcompress SpriteTex/lift_buranko.arc.LH -x -o SpriteTex/lift_buranko.arc
ntcompress SpriteTex/lift_intore.arc.LH -x -o SpriteTex/lift_intore.arc
ntcompress SpriteTex/lift_taru.arc.LH -x -o SpriteTex/lift_taru.arc
ntcompress SpriteTex/lift_torokko.arc.LH -x -o SpriteTex/lift_torokko.arc
ntcompress SpriteTex/lift_trampoline.arc.LH -x -o SpriteTex/lift_trampoline.arc
ntcompress SpriteTex/lift_yogan_kinoko.arc.LH -x -o SpriteTex/lift_yogan_kinoko.arc
ntcompress SpriteTex/lift_zen.arc.LH -x -o SpriteTex/lift_zen.arc
ntcompress SpriteTex/lift_zen_color_pori.arc.LH -x -o SpriteTex/lift_zen_color_pori.arc
ntcompress SpriteTex/Luigi.arc.LH -x -o SpriteTex/Luigi.arc
ntcompress SpriteTex/manjirou.arc.LH -x -o SpriteTex/manjirou.arc
ntcompress SpriteTex/Mario.arc.LH -x -o SpriteTex/Mario.arc
ntcompress SpriteTex/met.arc.LH -x -o SpriteTex/met.arc
ntcompress SpriteTex/met_pata.arc.LH -x -o SpriteTex/met_pata.arc
ntcompress SpriteTex/met_pataBig.arc.LH -x -o SpriteTex/met_pataBig.arc
ntcompress SpriteTex/met_toge.arc.LH -x -o SpriteTex/met_toge.arc
ntcompress SpriteTex/middle_flag.arc.LH -x -o SpriteTex/middle_flag.arc
ntcompress SpriteTex/mrsun.arc.LH -x -o SpriteTex/mrsun.arc
ntcompress SpriteTex/nokonokoA.arc.LH -x -o SpriteTex/nokonokoA.arc
ntcompress SpriteTex/obj_coin.arc.LH -x -o SpriteTex/obj_coin.arc
ntcompress SpriteTex/obj_Hgear.arc.LH -x -o SpriteTex/obj_Hgear.arc
ntcompress SpriteTex/obj_kinoko.arc.LH -x -o SpriteTex/obj_kinoko.arc
ntcompress SpriteTex/obj_turara_rakka_Big.arc.LH -x -o SpriteTex/obj_turara_rakka_Big.arc
ntcompress SpriteTex/OpeningScene.arc.LH -x -o SpriteTex/OpeningScene.arc
ntcompress SpriteTex/P_rcha.arc.LH -x -o SpriteTex/P_rcha.arc
ntcompress SpriteTex/pukupuku.arc.LH -x -o SpriteTex/pukupuku.arc
ntcompress SpriteTex/pumpkin.arc.LH -x -o SpriteTex/pumpkin.arc
ntcompress SpriteTex/sanbo.arc.LH -x -o SpriteTex/sanbo.arc
ntcompress SpriteTex/shyguy.arc.LH -x -o SpriteTex/shyguy.arc
ntcompress SpriteTex/Shynja.arc.LH -x -o SpriteTex/Shynja.arc
ntcompress SpriteTex/StarRing.arc.LH -x -o SpriteTex/StarRing.arc
ntcompress SpriteTex/switch.arc.LH -x -o SpriteTex/switch.arc
ntcompress SpriteTex/switch_koopa.arc.LH -x -o SpriteTex/switch_koopa.arc
ntcompress SpriteTex/tcloud.arc.LH -x -o SpriteTex/tcloud.arc
ntcompress SpriteTex/teresa.arc.LH -x -o SpriteTex/teresa.arc
ntcompress SpriteTex/test_lift.arc.LH -x -o SpriteTex/test_lift.arc
ntcompress SpriteTex/togezo.arc.LH -x -o SpriteTex/togezo.arc
ntcompress SpriteTex/topman.arc.LH -x -o SpriteTex/topman.arc
ntcompress SpriteTex/Y_TexGreen.arc.LH -x -o SpriteTex/Y_TexGreen.arc
ntcompress Tilesets/Cloudscape.arc.LH -x -o Tilesets/Cloudscape.arc
ntcompress Tilesets/CrackedMega.arc.LH -x -o Tilesets/CrackedMega.arc
ntcompress Tilesets/ghostrocks.arc.LH -x -o Tilesets/ghostrocks.arc
ntcompress Tilesets/Pa0_jyotyu.arc.LH -x -o Tilesets/Pa0_jyotyu.arc
ntcompress Tilesets/Pa0_jyotyu_chika.arc.LH -x -o Tilesets/Pa0_jyotyu_chika.arc
ntcompress Tilesets/Pa0_jyotyu_setsugen.arc.LH -x -o Tilesets/Pa0_jyotyu_setsugen.arc
ntcompress Tilesets/Pa0_jyotyu_yougan.arc.LH -x -o Tilesets/Pa0_jyotyu_yougan.arc
ntcompress Tilesets/Pa0_OhFuckIhopeThisWorks.arc.LH -x -o Tilesets/Pa0_OhFuckIhopeThisWorks.arc
ntcompress Tilesets/Pa0_WSELTS.arc.LH -x -o Tilesets/Pa0_WSELTS.arc
ntcompress Tilesets/Pa1_autumncastle.arc.LH -x -o Tilesets/Pa1_autumncastle.arc
ntcompress Tilesets/Pa1_autumnmega.arc.LH -x -o Tilesets/Pa1_autumnmega.arc
ntcompress Tilesets/Pa1_bluegake.arc.LH -x -o Tilesets/Pa1_bluegake.arc
ntcompress Tilesets/Pa1_challenge.arc.LH -x -o Tilesets/Pa1_challenge.arc
ntcompress Tilesets/Pa1_chika.arc.LH -x -o Tilesets/Pa1_chika.arc
ntcompress Tilesets/Pa1_chika2.arc.LH -x -o Tilesets/Pa1_chika2.arc
ntcompress Tilesets/Pa1_cracks.arc.LH -x -o Tilesets/Pa1_cracks.arc
ntcompress Tilesets/Pa1_CreditsMishMash.arc.LH -x -o Tilesets/Pa1_CreditsMishMash.arc
ntcompress Tilesets/Pa1_daishizen.arc.LH -x -o Tilesets/Pa1_daishizen.arc
ntcompress Tilesets/Pa1_daishizenkuri.arc.LH -x -o Tilesets/Pa1_daishizenkuri.arc
ntcompress Tilesets/Pa1_darkmtmush.arc.LH -x -o Tilesets/Pa1_darkmtmush.arc
ntcompress Tilesets/Pa1_dessert.arc.LH -x -o Tilesets/Pa1_dessert.arc
ntcompress Tilesets/Pa1_dokan_naibu.arc.LH -x -o Tilesets/Pa1_dokan_naibu.arc
ntcompress Tilesets/Pa1_dokan_naibu_prpl.arc.LH -x -o Tilesets/Pa1_dokan_naibu_prpl.arc
ntcompress Tilesets/Pa1_e3setsugen.arc.LH -x -o Tilesets/Pa1_e3setsugen.arc
ntcompress Tilesets/Pa1_freezeflame.arc.LH -x -o Tilesets/Pa1_freezeflame.arc
ntcompress Tilesets/Pa1_gake.arc.LH -x -o Tilesets/Pa1_gake.arc
ntcompress Tilesets/Pa1_gake_yougan.arc.LH -x -o Tilesets/Pa1_gake_yougan.arc
ntcompress Tilesets/Pa1_ghostship.arc.LH -x -o Tilesets/Pa1_ghostship.arc
ntcompress Tilesets/Pa1_graveyard.arc.LH -x -o Tilesets/Pa1_graveyard.arc
ntcompress Tilesets/Pa1_hikousen.arc.LH -x -o Tilesets/Pa1_hikousen.arc
ntcompress Tilesets/Pa1_hikousen2.arc.LH -x -o Tilesets/Pa1_hikousen2.arc
ntcompress Tilesets/Pa1_japantemple.arc.LH -x -o Tilesets/Pa1_japantemple.arc
ntcompress Tilesets/Pa1_jungleruins.arc.LH -x -o Tilesets/Pa1_jungleruins.arc
ntcompress Tilesets/Pa1_kaigan.arc.LH -x -o Tilesets/Pa1_kaigan.arc
ntcompress Tilesets/Pa1_kaiganplus.arc.LH -x -o Tilesets/Pa1_kaiganplus.arc
ntcompress Tilesets/Pa1_koopa_out.arc.LH -x -o Tilesets/Pa1_koopa_out.arc
ntcompress Tilesets/Pa1_korichika.arc.LH -x -o Tilesets/Pa1_korichika.arc
ntcompress Tilesets/Pa1_kurayami_chika.arc.LH -x -o Tilesets/Pa1_kurayami_chika.arc
ntcompress Tilesets/Pa1_Kyandi.arc.LH -x -o Tilesets/Pa1_Kyandi.arc
ntcompress Tilesets/Pa1_lavaglow.arc.LH -x -o Tilesets/Pa1_lavaglow.arc
ntcompress Tilesets/Pa1_magicsnow.arc.LH -x -o Tilesets/Pa1_magicsnow.arc
ntcompress Tilesets/Pa1_metaltower.arc.LH -x -o Tilesets/Pa1_metaltower.arc
ntcompress Tilesets/Pa1_Mountainb.arc.LH -x -o Tilesets/Pa1_Mountainb.arc
ntcompress Tilesets/Pa1_Mountains.arc.LH -x -o Tilesets/Pa1_Mountains.arc
ntcompress Tilesets/Pa1_mtmush.arc.LH -x -o Tilesets/Pa1_mtmush.arc
ntcompress Tilesets/Pa1_mushcastle.arc.LH -x -o Tilesets/Pa1_mushcastle.arc
ntcompress Tilesets/Pa1_mushtower.arc.LH -x -o Tilesets/Pa1_mushtower.arc
ntcompress Tilesets/Pa1_newnohara.arc.LH -x -o Tilesets/Pa1_newnohara.arc
ntcompress Tilesets/Pa1_nohara.arc.LH -x -o Tilesets/Pa1_nohara.arc
ntcompress Tilesets/Pa1_nohara2.arc.LH -x -o Tilesets/Pa1_nohara2.arc
ntcompress Tilesets/Pa1_obake.arc.LH -x -o Tilesets/Pa1_obake.arc
ntcompress Tilesets/Pa1_obake_soto.arc.LH -x -o Tilesets/Pa1_obake_soto.arc
ntcompress Tilesets/Pa1_obake_soto_plus.arc.LH -x -o Tilesets/Pa1_obake_soto_plus.arc
ntcompress Tilesets/Pa1_peach_castle.arc.LH -x -o Tilesets/Pa1_peach_castle.arc
ntcompress Tilesets/Pa1_pumpkin.arc.LH -x -o Tilesets/Pa1_pumpkin.arc
ntcompress Tilesets/Pa1_pyramid2.arc.LH -x -o Tilesets/Pa1_pyramid2.arc
ntcompress Tilesets/Pa1_redcave.arc.LH -x -o Tilesets/Pa1_redcave.arc
ntcompress Tilesets/Pa1_risingsun.arc.LH -x -o Tilesets/Pa1_risingsun.arc
ntcompress Tilesets/Pa1_sabaku.arc.LH -x -o Tilesets/Pa1_sabaku.arc
ntcompress Tilesets/Pa1_sabaku_chika.arc.LH -x -o Tilesets/Pa1_sabaku_chika.arc
ntcompress Tilesets/Pa1_setsugen.arc.LH -x -o Tilesets/Pa1_setsugen.arc
ntcompress Tilesets/Pa1_shiro.arc.LH -x -o Tilesets/Pa1_shiro.arc
ntcompress Tilesets/Pa1_shiro_boss1.arc.LH -x -o Tilesets/Pa1_shiro_boss1.arc
ntcompress Tilesets/Pa1_shiro_koopa.arc.LH -x -o Tilesets/Pa1_shiro_koopa.arc
ntcompress Tilesets/Pa1_shroomship.arc.LH -x -o Tilesets/Pa1_shroomship.arc
ntcompress Tilesets/Pa1_sinkybg.arc.LH -x -o Tilesets/Pa1_sinkybg.arc
ntcompress Tilesets/Pa1_snowfort.arc.LH -x -o Tilesets/Pa1_snowfort.arc
ntcompress Tilesets/Pa1_snowship.arc.LH -x -o Tilesets/Pa1_snowship.arc
ntcompress Tilesets/Pa1_space.arc.LH -x -o Tilesets/Pa1_space.arc
ntcompress Tilesets/Pa1_springwater.arc.LH -x -o Tilesets/Pa1_springwater.arc
ntcompress Tilesets/Pa1_StarHaven.arc.LH -x -o Tilesets/Pa1_StarHaven.arc
ntcompress Tilesets/Pa1_StarRoad.arc.LH -x -o Tilesets/Pa1_StarRoad.arc
ntcompress Tilesets/Pa1_suichu.arc.LH -x -o Tilesets/Pa1_suichu.arc
ntcompress Tilesets/Pa1_suichu_lightblue.arc.LH -x -o Tilesets/Pa1_suichu_lightblue.arc
ntcompress Tilesets/Pa1_suichu_prp.arc.LH -x -o Tilesets/Pa1_suichu_prp.arc
ntcompress Tilesets/Pa1_tanks.arc.LH -x -o Tilesets/Pa1_tanks.arc
ntcompress Tilesets/Pa1_toride.arc.LH -x -o Tilesets/Pa1_toride.arc
ntcompress Tilesets/Pa1_toride_boss2.arc.LH -x -o Tilesets/Pa1_toride_boss2.arc
ntcompress Tilesets/Pa1_toytown2.arc.LH -x -o Tilesets/Pa1_toytown2.arc
ntcompress Tilesets/Pa1_tswsele.arc.LH -x -o Tilesets/Pa1_tswsele.arc
ntcompress Tilesets/Pa2_autumn4.arc.LH -x -o Tilesets/Pa2_autumn4.arc
ntcompress Tilesets/Pa2_bgmagicsnow.arc.LH -x -o Tilesets/Pa2_bgmagicsnow.arc
ntcompress Tilesets/Pa2_bigpipes.arc.LH -x -o Tilesets/Pa2_bigpipes.arc
ntcompress Tilesets/Pa2_Brickz.arc.LH -x -o Tilesets/Pa2_Brickz.arc
ntcompress Tilesets/Pa2_bridge++.arc.LH -x -o Tilesets/Pa2_bridge++.arc
ntcompress Tilesets/Pa2_castle_final.arc -x -o Tilesets/Pa2_castle_final.arc
ntcompress Tilesets/Pa2_ClockBG.arc.LH -x -o Tilesets/Pa2_ClockBG.arc
ntcompress Tilesets/pa2_clouds.arc.LH -x -o Tilesets/pa2_clouds.arc
ntcompress Tilesets/Pa2_CreditsMishMashUgh.arc.LH -x -o Tilesets/Pa2_CreditsMishMashUgh.arc
ntcompress Tilesets/Pa2_crystalcastle.arc.LH -x -o Tilesets/Pa2_crystalcastle.arc
ntcompress Tilesets/Pa2_darkcave.arc.LH -x -o Tilesets/Pa2_darkcave.arc
ntcompress Tilesets/Pa2_dbkori_freezeflameundgrnd_t.arc.LH -x -o Tilesets/Pa2_dbkori_freezeflameundgrnd_t.arc
ntcompress Tilesets/Pa2_dokan_naibu_PRPL.arc.LH -x -o Tilesets/Pa2_dokan_naibu_PRPL.arc
ntcompress Tilesets/Pa2_doukutu_prpl.arc.LH -x -o Tilesets/Pa2_doukutu_prpl.arc
ntcompress Tilesets/Pa2_doukutu.arc.LH -x -o Tilesets/Pa2_doukutu.arc
ntcompress Tilesets/Pa2_doukutu2.arc.LH -x -o Tilesets/Pa2_doukutu2.arc
ntcompress Tilesets/Pa2_doukutu3.arc.LH -x -o Tilesets/Pa2_doukutu3.arc
ntcompress Tilesets/Pa2_doukutu4.arc.LH -x -o Tilesets/Pa2_doukutu4.arc
ntcompress Tilesets/Pa2_doukutu5.arc.LH -x -o Tilesets/Pa2_doukutu5.arc
ntcompress Tilesets/Pa2_doukutu6.arc.LH -x -o Tilesets/Pa2_doukutu6.arc
ntcompress Tilesets/Pa2_forestobake.arc.LH -x -o Tilesets/Pa2_forestobake.arc
ntcompress Tilesets/Pa2_gake.arc.LH -x -o Tilesets/Pa2_gake.arc
ntcompress Tilesets/Pa2_ghostcastle.arc.LH -x -o Tilesets/Pa2_ghostcastle.arc
ntcompress Tilesets/Pa2_ghostship.arc.LH -x -o Tilesets/Pa2_ghostship.arc
ntcompress Tilesets/Pa2_ghostwoods.arc.LH -x -o Tilesets/Pa2_ghostwoods.arc
ntcompress Tilesets/Pa2_hikousen.arc.LH -x -o Tilesets/Pa2_hikousen.arc
ntcompress Tilesets/Pa2_hikousen2.arc.LH -x -o Tilesets/Pa2_hikousen2.arc
ntcompress Tilesets/Pa2_hikousen_coal.arc.LH -x -o Tilesets/Pa2_hikousen_coal.arc
ntcompress Tilesets/Pa2_hikousen2swap.arc.LH -x -o Tilesets/Pa2_hikousen2swap.arc
ntcompress Tilesets/Pa2_ice.arc.LH -x -o Tilesets/Pa2_ice.arc
ntcompress Tilesets/Pa2_icyledges.arc.LH -x -o Tilesets/Pa2_icyledges.arc
ntcompress Tilesets/Pa2_japantemple_bg.arc.LH -x -o Tilesets/Pa2_japantemple_bg.arc
ntcompress Tilesets/Pa2_kinoko.arc.LH -x -o Tilesets/Pa2_kinoko.arc
ntcompress Tilesets/Pa2_kori.arc.LH -x -o Tilesets/Pa2_kori.arc
ntcompress Tilesets/Pa2_lavasnow.arc.LH -x -o Tilesets/Pa2_lavasnow.arc
ntcompress Tilesets/Pa2_lessopacolors.arc.LH -x -o Tilesets/Pa2_lessopacolors.arc
ntcompress Tilesets/Pa2_magicsnow.arc.LH -x -o Tilesets/Pa2_magicsnow.arc
ntcompress Tilesets/Pa2_mtbushb.arc.LH -x -o Tilesets/Pa2_mtbushb.arc
ntcompress Tilesets/Pa2_Pa2mega.arc.LH -x -o Tilesets/Pa2_Pa2mega.arc
ntcompress Tilesets/Pa2_Pyramid.arc.LH -x -o Tilesets/Pa2_Pyramid.arc
ntcompress Tilesets/Pa2_risingsunPT.arc.LH -x -o Tilesets/Pa2_risingsunPT.arc
ntcompress Tilesets/Pa2_risingsuntemple.arc.LH -x -o Tilesets/Pa2_risingsuntemple.arc
ntcompress Tilesets/Pa2_sewerpipes.arc.LH -x -o Tilesets/Pa2_sewerpipes.arc
ntcompress Tilesets/Pa2_shroomship.arc.LH -x -o Tilesets/Pa2_shroomship.arc
ntcompress Tilesets/Pa2_sinkypyramid.arc.LH -x -o Tilesets/Pa2_sinkypyramid.arc
ntcompress TileSets/Pa2_snowship.arc.LH -x -o TileSets/Pa2_snowship.arc
ntcompress TileSets/Pa2_sora.arc.LH -x -o TileSets/Pa2_sora.arc
ntcompress TileSets/Pa2_springwater.arc.LH -x -o TileSets/Pa2_springwater.arc
ntcompress Tilesets/Pa2_stalagmites.arc.LH -x -o Tilesets/Pa2_stalagmites.arc
ntcompress Tilesets/Pa2_StarBackdrop.arc.LH -x -o Tilesets/Pa2_StarBackdrop.arc
ntcompress Tilesets/Pa2_statues.arc.LH -x -o Tilesets/Pa2_statues.arc
ntcompress Tilesets/Pa2_Tangletree.arc.LH -x -o Tilesets/Pa2_Tangletree.arc
ntcompress Tilesets/Pa2_tank.arc.LH -x -o Tilesets/Pa2_tank.arc
ntcompress Tilesets/Pa2_ToadHouse.arc.LH -x -o Tilesets/Pa2_ToadHouse.arc
ntcompress Tilesets/Pa2_volcanobg.arc.LH -x -o Tilesets/Pa2_volcanobg.arc
ntcompress Tilesets/Pa2_yoshihaus.arc.LH -x -o Tilesets/Pa2_yoshihaus.arc
ntcompress Tilesets/Pa3_autumnbg.arc.LH -x -o Tilesets/Pa3_autumnbg.arc
ntcompress Tilesets/Pa3_autumncastle.arc.LH -x -o Tilesets/Pa3_autumncastle.arc
ntcompress Tilesets/Pa3_beehive.arc.LH -x -o Tilesets/Pa3_beehive.arc
ntcompress Tilesets/Pa3_Bent_Shrooms.arc.LH -x -o Tilesets/Pa3_Bent_Shrooms.arc
ntcompress Tilesets/Pa3_bigpipes.arc.LH -x -o Tilesets/Pa3_bigpipes.arc
ntcompress Tilesets/Pa3_bigpipesb.arc.LH -x -o Tilesets/Pa3_bigpipesb.arc
ntcompress Tilesets/Pa3_ClockBG.arc.LH -x -o Tilesets/Pa3_ClockBG.arc
ntcompress Tilesets/Pa3_CreditsMishMashFinally.arc.LH -x -o Tilesets/Pa3_CreditsMishMashFinally.arc
ntcompress Tilesets/Pa3_daishizen.arc.LH -x -o Tilesets/Pa3_daishizen.arc
ntcompress Tilesets/Pa3_desertoasis.arc.LH -x -o Tilesets/Pa3_desertoasis.arc
ntcompress Tilesets/Pa3_doukutu.arc.LH -x -o Tilesets/Pa3_doukutu.arc
ntcompress Tilesets/Pa3_doukutu5.arc.LH -x -o Tilesets/Pa3_doukutu5.arc
ntcompress Tilesets/Pa3_doukutu6.arc.LH -x -o Tilesets/Pa3_doukutu6.arc
ntcompress Tilesets/Pa3_falls.arc.LH -x -o Tilesets/Pa3_falls.arc
ntcompress Tilesets/Pa3_finalcastlestuff2012.arc.LH -x -o Tilesets/Pa3_finalcastlestuff2012.arc
ntcompress Tilesets/Pa3_ghostship.arc.LH -x -o Tilesets/Pa3_ghostship.arc
ntcompress Tilesets/Pa3_graves.arc.LH -x -o Tilesets/Pa3_graves.arc
ntcompress Tilesets/Pa3_graveyars.arc.LH -x -o Tilesets/Pa3_graveyars.arc
ntcompress Tilesets/Pa3_hanatari_saka.arc.LH -x -o Tilesets/Pa3_hanatari_saka.arc
ntcompress Tilesets/Pa3_japantemple_specifictile.arc.LH -x -o Tilesets/Pa3_japantemple_specifictile.arc
ntcompress Tilesets/Pa3_jungleruins.arc.LH -x -o Tilesets/Pa3_jungleruins.arc
ntcompress Tilesets/Pa3_magicsnow.arc.LH -x -o Tilesets/Pa3_magicsnow.arc
ntcompress Tilesets/Pa3_MG_house_ami_rail.arc.LH -x -o Tilesets/Pa3_MG_house_ami_rail.arc
ntcompress Tilesets/Pa3_mtbush.arc.LH -x -o Tilesets/Pa3_mtbush.arc
ntcompress Tilesets/Pa3_mtbush_vines.arc.LH -x -o Tilesets/Pa3_mtbush_vines.arc
ntcompress Tilesets/Pa3_passthroughredstair.arc.LH -x -o Tilesets/Pa3_passthroughredstair.arc
ntcompress Tilesets/Pa3_pumpkin.arc.LH -x -o Tilesets/Pa3_pumpkin.arc
ntcompress Tilesets/Pa3_rail.arc.LH -x -o Tilesets/Pa3_rail.arc
ntcompress Tilesets/Pa3_rail_white.arc.LH -x -o Tilesets/Pa3_rail_white.arc
ntcompress Tilesets/Pa3_Railglow.arc.LH -x -o Tilesets/Pa3_Railglow.arc
ntcompress Tilesets/Pa3_Railglow_noanim.arc.LH -x -o Tilesets/Pa3_Railglow_noanim.arc
ntcompress Tilesets/Pa3_sandpitkgn.arc.LH -x -o Tilesets/Pa3_sandpitkgn.arc
ntcompress Tilesets/Pa3_springwater.arc.LH -x -o Tilesets/Pa3_springwater.arc
ntcompress Tilesets/Pa3_starblok.arc.LH -x -o Tilesets/Pa3_starblok.arc
ntcompress Tilesets/Pa3_Traps.arc.LH -x -o Tilesets/Pa3_Traps.arc
ntcompress Tilesets/Pa3_vines.arc.LH -x -o Tilesets/Pa3_vines.arc
ntcompress Tilesets/Pa3_waterworks.arc.LH -x -o Tilesets/Pa3_waterworks.arc
ntcompress Tilesets/Pa3_webs.arc.LH -x -o Tilesets/Pa3_webs.arc
ntcompress Tilesets/Pa3_yoshiforest.arc.LH -x -o Tilesets/Pa3_yoshiforest.arc
ntcompress TitleReplay/01-01_1.bin.LH -x -o TitleReplay/01-01_1.bin
ntcompress TitleReplay/01-03_1.bin.LH -x -o TitleReplay/01-03_1.bin
ntcompress TitleReplay/01-03_2.bin.LH -x -o TitleReplay/01-03_2.bin
ntcompress TitleReplay/01-03_3.bin.LH -x -o TitleReplay/01-03_3.bin
ntcompress TitleReplay/01-03_4.bin.LH -x -o TitleReplay/01-03_4.bin
ntcompress TitleReplay/02-02_1.bin.LH -x -o TitleReplay/02-02_1.bin
ntcompress TitleReplay/02-05_1.bin.LH -x -o TitleReplay/02-05_1.bin
ntcompress TitleReplay/03-03_1.bin.LH -x -o TitleReplay/03-03_1.bin
ntcompress TitleReplay/03-03_2.bin.LH -x -o TitleReplay/03-03_2.bin
ntcompress TitleReplay/03-03_3.bin.LH -x -o TitleReplay/03-03_3.bin
ntcompress TitleReplay/03-03_4.bin.LH -x -o TitleReplay/03-03_4.bin
ntcompress TitleReplay/04-02_1.bin.LH -x -o TitleReplay/04-02_1.bin
ntcompress TitleReplay/04-02_2.bin.LH -x -o TitleReplay/04-02_2.bin
ntcompress TitleReplay/04-02_3.bin.LH -x -o TitleReplay/04-02_3.bin
ntcompress TitleReplay/04-02_4.bin.LH -x -o TitleReplay/04-02_4.bin
ntcompress TitleReplay/04-07_1.bin.LH -x -o TitleReplay/04-07_1.bin
ntcompress TitleReplay/04-07_2.bin.LH -x -o TitleReplay/04-07_2.bin
ntcompress TitleReplay/04-07_3.bin.LH -x -o TitleReplay/04-07_3.bin
ntcompress TitleReplay/04-07_4.bin.LH -x -o TitleReplay/04-07_4.bin
ntcompress TitleReplay/05-01_1.bin.LH -x -o TitleReplay/05-01_1.bin
ntcompress TitleReplay/05-01_2.bin.LH -x -o TitleReplay/05-01_2.bin
ntcompress TitleReplay/05-01_3.bin.LH -x -o TitleReplay/05-01_3.bin
ntcompress TitleReplay/05-01_4.bin.LH -x -o TitleReplay/05-01_4.bin
ntcompress TitleReplay/05-03_1.bin.LH -x -o TitleReplay/05-03_1.bin
ntcompress TitleReplay/05-03_2.bin.LH -x -o TitleReplay/05-03_2.bin
ntcompress TitleReplay/05-03_3.bin.LH -x -o TitleReplay/05-03_3.bin
ntcompress TitleReplay/05-03_4.bin.LH -x -o TitleReplay/05-03_4.bin
ntcompress TitleReplay/06-02_1.bin.LH -x -o TitleReplay/06-02_1.bin
ntcompress TitleReplay/06-04_1.bin.LH -x -o TitleReplay/06-04_1.bin
ntcompress TitleReplay/06-04_2.bin.LH -x -o TitleReplay/06-04_2.bin
ntcompress TitleReplay/06-04_3.bin.LH -x -o TitleReplay/06-04_3.bin
ntcompress TitleReplay/06-04_4.bin.LH -x -o TitleReplay/06-04_4.bin
ntcompress TitleReplay/07-01_1.bin.LH -x -o TitleReplay/07-01_1.bin
ntcompress TitleReplay/07-02_1.bin.LH -x -o TitleReplay/07-02_1.bin
ntcompress TitleReplay/10-01_1.bin.LH -x -o TitleReplay/10-01_1.bin
GOTO END


:LZ
ntcompress Stages/01-01.arc.LZ -x -o Stages/01-01.arc
ntcompress Stages/01-02.arc.LZ -x -o Stages/01-02.arc
ntcompress Stages/01-03.arc.LZ -x -o Stages/01-03.arc
ntcompress Stages/01-04.arc.LZ -x -o Stages/01-04.arc
ntcompress Stages/01-05.arc.LZ -x -o Stages/01-05.arc 
ntcompress Stages/01-06.arc.LZ -x -o Stages/01-06.arc 
ntcompress Stages/01-07.arc.LZ -x -o Stages/01-07.arc 
ntcompress Stages/01-08.arc.LZ -x -o Stages/01-08.arc 
ntcompress Stages/01-09.arc.LZ -x -o Stages/01-09.arc 
ntcompress Stages/01-10.arc.LZ -x -o Stages/01-10.arc 
ntcompress Stages/01-11.arc.LZ -x -o Stages/01-11.arc 
ntcompress Stages/01-12.arc.LZ -x -o Stages/01-12.arc 
ntcompress Stages/01-13.arc.LZ -x -o Stages/01-13.arc 
ntcompress Stages/01-14.arc.LZ -x -o Stages/01-14.arc 
ntcompress Stages/01-15.arc.LZ -x -o Stages/01-15.arc 
ntcompress Stages/01-25.arc.LZ -x -o Stages/01-25.arc 
ntcompress Stages/01-31.arc.LZ -x -o Stages/01-31.arc 
ntcompress Stages/01-33.arc.LZ -x -o Stages/01-33.arc
ntcompress Stages/01-34.arc.LZ -x -o Stages/01-34.arc
ntcompress Stages/01-38.arc.LZ -x -o Stages/01-38.arc
ntcompress Stages/01-40.arc.LZ -x -o Stages/01-40.arc 
ntcompress Stages/01-41.arc.LZ -x -o Stages/01-41.arc 
ntcompress Stages/01-42.arc.LZ -x -o Stages/01-42.arc 
ntcompress Stages/01-99.arc.LZ -x -o Stages/01-99.arc 
ntcompress Stages/02-01.arc.LZ -x -o Stages/02-01.arc
ntcompress Stages/02-02.arc.LZ -x -o Stages/02-02.arc
ntcompress Stages/02-03.arc.LZ -x -o Stages/02-03.arc
ntcompress Stages/02-04.arc.LZ -x -o Stages/02-04.arc
ntcompress Stages/02-05.arc.LZ -x -o Stages/02-05.arc
ntcompress Stages/02-06.arc.LZ -x -o Stages/02-06.arc
ntcompress Stages/02-07.arc.LZ -x -o Stages/02-07.arc
ntcompress Stages/02-08.arc.LZ -x -o Stages/02-08.arc
ntcompress Stages/02-09.arc.LZ -x -o Stages/02-09.arc
ntcompress Stages/02-10.arc.LZ -x -o Stages/02-10.arc
ntcompress Stages/02-11.arc.LZ -x -o Stages/02-11.arc
ntcompress Stages/02-12.arc.LZ -x -o Stages/02-12.arc
ntcompress Stages/02-13.arc.LZ -x -o Stages/02-13.arc
ntcompress Stages/02-14.arc.LZ -x -o Stages/02-14.arc
ntcompress Stages/02-15.arc.LZ -x -o Stages/02-15.arc
ntcompress Stages/02-25.arc.LZ -x -o Stages/02-25.arc
ntcompress Stages/02-33.arc.LZ -x -o Stages/02-33.arc
ntcompress Stages/02-34.arc.LZ -x -o Stages/02-34.arc
ntcompress Stages/02-38.arc.LZ -x -o Stages/02-38.arc
ntcompress Stages/02-41.arc.LZ -x -o Stages/02-41.arc
ntcompress Stages/02-99.arc.LZ -x -o Stages/02-99.arc
ntcompress Stages/03-01.arc.LZ -x -o Stages/03-01.arc
ntcompress Stages/03-02.arc.LZ -x -o Stages/03-02.arc
ntcompress Stages/03-04.arc.LZ -x -o Stages/03-04.arc
ntcompress Stages/03-03.arc.LZ -x -o Stages/03-03.arc
ntcompress Stages/03-05.arc.LZ -x -o Stages/03-05.arc
ntcompress Stages/03-06.arc.LZ -x -o Stages/03-06.arc
ntcompress Stages/03-07.arc.LZ -x -o Stages/03-07.arc
ntcompress Stages/03-09.arc.LZ -x -o Stages/03-09.arc
ntcompress Stages/03-08.arc.LZ -x -o Stages/03-08.arc
ntcompress Stages/03-10.arc.LZ -x -o Stages/03-10.arc
ntcompress Stages/03-11.arc.LZ -x -o Stages/03-11.arc
ntcompress Stages/03-12.arc.LZ -x -o Stages/03-12.arc
ntcompress Stages/03-14.arc.LZ -x -o Stages/03-14.arc
ntcompress Stages/03-13.arc.LZ -x -o Stages/03-13.arc
ntcompress Stages/03-25.arc.LZ -x -o Stages/03-25.arc
ntcompress Stages/03-15.arc.LZ -x -o Stages/03-15.arc
ntcompress Stages/03-33.arc.LZ -x -o Stages/03-33.arc
ntcompress Stages/03-34.arc.LZ -x -o Stages/03-34.arc
ntcompress Stages/03-38.arc.LZ -x -o Stages/03-38.arc
ntcompress Stages/03-99.arc.LZ -x -o Stages/03-99.arc
ntcompress Stages/04-01.arc.LZ -x -o Stages/04-01.arc
ntcompress Stages/04-02.arc.LZ -x -o Stages/04-02.arc
ntcompress Stages/04-03.arc.LZ -x -o Stages/04-03.arc
ntcompress Stages/04-04.arc.LZ -x -o Stages/04-04.arc
ntcompress Stages/04-05.arc.LZ -x -o Stages/04-05.arc
ntcompress Stages/04-06.arc.LZ -x -o Stages/04-06.arc
ntcompress Stages/04-07.arc.LZ -x -o Stages/04-07.arc
ntcompress Stages/04-08.arc.LZ -x -o Stages/04-08.arc
ntcompress Stages/04-09.arc.LZ -x -o Stages/04-09.arc
ntcompress Stages/04-10.arc.LZ -x -o Stages/04-10.arc
ntcompress Stages/04-11.arc.LZ -x -o Stages/04-11.arc
ntcompress Stages/04-12.arc.LZ -x -o Stages/04-12.arc
ntcompress Stages/04-15.arc.LZ -x -o Stages/04-15.arc
ntcompress Stages/04-25.arc.LZ -x -o Stages/04-25.arc
ntcompress Stages/04-31.arc.LZ -x -o Stages/04-31.arc
ntcompress Stages/04-33.arc.LZ -x -o Stages/04-33.arc
ntcompress Stages/04-34.arc.LZ -x -o Stages/04-34.arc
ntcompress Stages/04-38.arc.LZ -x -o Stages/04-38.arc
ntcompress Stages/04-99.arc.LZ -x -o Stages/04-99.arc
ntcompress Stages/05-01.arc.LZ -x -o Stages/05-01.arc
ntcompress Stages/05-02.arc.LZ -x -o Stages/05-02.arc
ntcompress Stages/05-03.arc.LZ -x -o Stages/05-03.arc
ntcompress Stages/05-04.arc.LZ -x -o Stages/05-04.arc
ntcompress Stages/05-05.arc.LZ -x -o Stages/05-05.arc
ntcompress Stages/05-06.arc.LZ -x -o Stages/05-06.arc
ntcompress Stages/05-07.arc.LZ -x -o Stages/05-07.arc
ntcompress Stages/05-08.arc.LZ -x -o Stages/05-08.arc
ntcompress Stages/05-09.arc.LZ -x -o Stages/05-09.arc
ntcompress Stages/05-10.arc.LZ -x -o Stages/05-10.arc
ntcompress Stages/05-11.arc.LZ -x -o Stages/05-11.arc
ntcompress Stages/05-15.arc.LZ -x -o Stages/05-15.arc
ntcompress Stages/05-25.arc.LZ -x -o Stages/05-25.arc
ntcompress Stages/05-33.arc.LZ -x -o Stages/05-33.arc
ntcompress Stages/05-34.arc.LZ -x -o Stages/05-34.arc
ntcompress Stages/05-99.arc.LZ -x -o Stages/05-99.arc
ntcompress Stages/05-38.arc.LZ -x -o Stages/05-38.arc
ntcompress Stages/06-01.arc.LZ -x -o Stages/06-01.arc
ntcompress Stages/06-02.arc.LZ -x -o Stages/06-02.arc
ntcompress Stages/06-03.arc.LZ -x -o Stages/06-03.arc
ntcompress Stages/06-04.arc.LZ -x -o Stages/06-04.arc
ntcompress Stages/06-05.arc.LZ -x -o Stages/06-05.arc
ntcompress Stages/06-06.arc.LZ -x -o Stages/06-06.arc
ntcompress Stages/06-07.arc.LZ -x -o Stages/06-07.arc
ntcompress Stages/06-08.arc.LZ -x -o Stages/06-08.arc
ntcompress Stages/06-09.arc.LZ -x -o Stages/06-09.arc
ntcompress Stages/06-15.arc.LZ -x -o Stages/06-15.arc
ntcompress Stages/06-24.arc.LZ -x -o Stages/06-24.arc 
ntcompress Stages/06-25.arc.LZ -x -o Stages/06-25.arc
ntcompress Stages/06-33.arc.LZ -x -o Stages/06-33.arc
ntcompress Stages/06-34.arc.LZ -x -o Stages/06-34.arc
ntcompress Stages/06-38.arc.LZ -x -o Stages/06-38.arc
ntcompress Stages/06-99.arc.LZ -x -o Stages/06-99.arc
ntcompress Stages/07-01.arc.LZ -x -o Stages/07-01.arc
ntcompress Stages/07-02.arc.LZ -x -o Stages/07-02.arc
ntcompress Stages/07-03.arc.LZ -x -o Stages/07-03.arc
ntcompress Stages/07-05.arc.LZ -x -o Stages/07-05.arc
ntcompress Stages/07-06.arc.LZ -x -o Stages/07-06.arc
ntcompress Stages/07-07.arc.LZ -x -o Stages/07-07.arc
ntcompress Stages/07-04.arc.LZ -x -o Stages/07-04.arc
ntcompress Stages/07-08.arc.LZ -x -o Stages/07-08.arc
ntcompress Stages/07-15.arc.LZ -x -o Stages/07-15.arc
ntcompress Stages/07-25.arc.LZ -x -o Stages/07-25.arc
ntcompress Stages/07-31.arc.LZ -x -o Stages/07-31.arc
ntcompress Stages/07-33.arc.LZ -x -o Stages/07-33.arc
ntcompress Stages/07-34.arc.LZ -x -o Stages/07-34.arc
ntcompress Stages/07-38.arc.LZ -x -o Stages/07-38.arc
ntcompress Stages/07-41.arc.LZ -x -o Stages/07-41.arc
ntcompress Stages/07-99.arc.LZ -x -o Stages/07-99.arc
ntcompress Stages/08-01.arc.LZ -x -o Stages/08-01.arc
ntcompress Stages/08-02.arc.LZ -x -o Stages/08-02.arc
ntcompress Stages/08-03.arc.LZ -x -o Stages/08-03.arc
ntcompress Stages/08-04.arc.LZ -x -o Stages/08-04.arc
ntcompress Stages/08-05.arc.LZ -x -o Stages/08-05.arc
ntcompress Stages/08-06.arc.LZ -x -o Stages/08-06.arc
ntcompress Stages/08-07.arc.LZ -x -o Stages/08-07.arc
ntcompress Stages/08-08.arc.LZ -x -o Stages/08-08.arc
ntcompress Stages/08-09.arc.LZ -x -o Stages/08-09.arc
ntcompress Stages/08-10.arc.LZ -x -o Stages/08-10.arc
ntcompress Stages/08-15.arc.LZ -x -o Stages/08-15.arc
ntcompress Stages/08-16.arc.LZ -x -o Stages/08-16.arc
ntcompress Stages/08-24.arc.LZ -x -o Stages/08-24.arc
ntcompress Stages/08-25.arc.LZ -x -o Stages/08-25.arc
ntcompress Stages/08-26.arc.LZ -x -o Stages/08-26.arc
ntcompress Stages/08-27.arc.LZ -x -o Stages/08-27.arc
ntcompress Stages/08-28.arc.LZ -x -o Stages/08-28.arc
ntcompress Stages/08-29.arc.LZ -x -o Stages/08-29.arc
ntcompress Stages/08-30.arc.LZ -x -o Stages/08-30.arc
ntcompress Stages/08-31.arc.LZ -x -o Stages/08-31.arc
ntcompress Stages/08-33.arc.LZ -x -o Stages/08-33.arc
ntcompress Stages/08-34.arc.LZ -x -o Stages/08-34.arc
ntcompress Stages/08-41.arc.LZ -x -o Stages/08-41.arc
ntcompress Stages/08-42.arc.LZ -x -o Stages/08-42.arc
ntcompress Stages/08-99.arc.LZ -x -o Stages/08-99.arc
ntcompress Stages/09-01.arc.LZ -x -o Stages/09-01.arc
ntcompress Stages/09-02.arc.LZ -x -o Stages/09-02.arc
ntcompress Stages/09-03.arc.LZ -x -o Stages/09-03.arc
ntcompress Stages/09-04.arc.LZ -x -o Stages/09-04.arc
ntcompress Stages/09-05.arc.LZ -x -o Stages/09-05.arc
ntcompress Stages/09-06.arc.LZ -x -o Stages/09-06.arc
ntcompress Stages/09-07.arc.LZ -x -o Stages/09-07.arc
ntcompress Stages/09-08.arc.LZ -x -o Stages/09-08.arc
ntcompress Stages/09-09.arc.LZ -x -o Stages/09-09.arc
ntcompress Stages/09-10.arc.LZ -x -o Stages/09-10.arc
ntcompress Stages/09-11.arc.LZ -x -o Stages/09-11.arc
ntcompress Stages/09-12.arc.LZ -x -o Stages/09-12.arc
ntcompress Stages/09-13.arc.LZ -x -o Stages/09-13.arc
ntcompress Stages/09-14.arc.LZ -x -o Stages/09-14.arc
ntcompress Stages/09-16.arc.LZ -x -o Stages/09-16.arc
ntcompress Stages/09-17.arc.LZ -x -o Stages/09-17.arc
ntcompress Stages/09-18.arc.LZ -x -o Stages/09-18.arc
ntcompress Stages/09-19.arc.LZ -x -o Stages/09-19.arc
ntcompress Stages/09-22.arc.LZ -x -o Stages/09-22.arc
ntcompress Stages/09-25.arc.LZ -x -o Stages/09-25.arc
ntcompress Stages/09-33.arc.LZ -x -o Stages/09-33.arc
ntcompress Stages/09-34.arc.LZ -x -o Stages/09-34.arc
ntcompress Stages/09-35.arc.LZ -x -o Stages/09-35.arc
ntcompress Stages/09-36.arc.LZ -x -o Stages/09-36.arc
ntcompress Stages/09-99.arc.LZ -x -o Stages/09-99.arc
ntcompress Stages/10-01.arc.LZ -x -o Stages/10-01.arc
ntcompress Stages/10-02.arc.LZ -x -o Stages/10-02.arc
ntcompress Stages/10-03.arc.LZ -x -o Stages/10-03.arc
ntcompress Stages/10-04.arc.LZ -x -o Stages/10-04.arc
ntcompress Stages/10-05.arc.LZ -x -o Stages/10-05.arc
ntcompress Stages/10-06.arc.LZ -x -o Stages/10-06.arc
ntcompress Stages/10-07.arc.LZ -x -o Stages/10-07.arc
ntcompress Stages/10-08.arc.LZ -x -o Stages/10-08.arc
ntcompress Stages/10-09.arc.LZ -x -o Stages/10-09.arc
ntcompress Stages/10-10.arc.LZ -x -o Stages/10-10.arc
ntcompress Stages/10-11.arc.LZ -x -o Stages/10-11.arc
ntcompress Stages/10-12.arc.LZ -x -o Stages/10-12.arc
ntcompress Stages/10-13.arc.LZ -x -o Stages/10-13.arc
ntcompress Stages/10-14.arc.LZ -x -o Stages/10-14.arc
ntcompress Stages/10-15.arc.LZ -x -o Stages/10-15.arc
ntcompress Stages/10-16.arc.LZ -x -o Stages/10-16.arc
ntcompress Stages/10-17.arc.LZ -x -o Stages/10-17.arc
ntcompress Stages/10-18.arc.LZ -x -o Stages/10-18.arc
ntcompress Stages/10-19.arc.LZ -x -o Stages/10-19.arc
ntcompress Stages/10-20.arc.LZ -x -o Stages/10-20.arc
ntcompress Stages/10-22.arc.LZ -x -o Stages/10-22.arc
ntcompress Stages/10-23.arc.LZ -x -o Stages/10-23.arc
ntcompress Stages/10-24.arc.LZ -x -o Stages/10-24.arc
ntcompress Stages/10-25.arc.LZ -x -o Stages/10-25.arc
ntcompress Stages/10-31.arc.LZ -x -o Stages/10-31.arc
ntcompress Stages/10-33.arc.LZ -x -o Stages/10-33.arc
ntcompress Stages/10-34.arc.LZ -x -o Stages/10-34.arc
ntcompress Stages/10-35.arc.LZ -x -o Stages/10-35.arc
ntcompress Stages/10-36.arc.LZ -x -o Stages/10-36.arc
ntcompress Stages/10-37.arc.LZ -x -o Stages/10-37.arc
ntcompress Stages/10-99.arc.LZ -x -o Stages/10-99.arc
ntcompress Layouts/classic.arc.LZ -x -o Layouts/classic.arc
ntcompress Layouts/coin.arc.LZ -x -o Layouts/coin.arc
ntcompress Layouts/corseClear.arc.LZ -x -o Layouts/corseClear.arc
ntcompress Layouts/MapHUD.arc.LZ -x -o Layouts/MapHUD.arc
ntcompress Layouts/msgbox.arc.LZ -x -o Layouts/msgbox.arc
ntcompress Layouts/shop.arc.LZ -x -o Layouts/shop.arc
ntcompress Layouts/StarCoins.arc.LZ -x -o Layouts/StarCoins.arc
ntcompress BGs/bgA_0B02.arc.LZ -x -o BGs/bgA_0B02.arc
ntcompress BGs/bgA_0C03.arc.LZ -x -o BGs/bgA_0C03.arc
ntcompress BGs/bgA_3DC2.arc.LZ -x -o BGs/bgA_3DC2.arc
ntcompress BGs/bgA_3F03.arc.LZ -x -o BGs/bgA_3F03.arc
ntcompress BGs/bgA_3FE2.arc.LZ -x -o BGs/bgA_3FE2.arc
ntcompress BGs/bgA_3FF2.arc.LZ -x -o BGs/bgA_3FF2.arc
ntcompress BGs/bgA_1003.arc.LZ -x -o BGs/bgA_1003.arc
ntcompress BGs/bgA_9986.arc.LZ -x -o BGs/bgA_9986.arc
ntcompress BGs/bgA_9989.arc.LZ -x -o BGs/bgA_9989.arc
ntcompress BGs/bgA_9990.arc.LZ -x -o BGs/bgA_9990.arc
ntcompress BGs/bgA_9995.arc.LZ -x -o BGs/bgA_9995.arc
ntcompress BGs/bgA_9998.arc.LZ -x -o BGs/bgA_9998.arc
ntcompress BGs/bgA_A602.arc.LZ -x -o BGs/bgA_A602.arc
ntcompress BGs/bgA_B602.arc.LZ -x -o BGs/bgA_B602.arc
ntcompress BGs/bgA_CCC1.arc.LZ -x -o BGs/bgA_CCC1.arc
ntcompress BGs/bgA_EFEF.arc.LZ -x -o BGs/bgA_EFEF.arc
ntcompress BGs/bgA_F1F2.arc.LZ -x -o BGs/bgA_F1F2.arc
ntcompress BGs/bgA_F949.arc.LZ -x -o BGs/bgA_F949.arc
ntcompress BGs/bgB_0CA2.arc.LZ -x -o BGs/bgB_0CA2.arc
ntcompress BGs/bgB_3FE2.arc.LZ -x -o BGs/bgB_3FE2.arc
ntcompress BGs/bgB_3FF2.arc.LZ -x -o BGs/bgB_3FF2.arc
ntcompress BGs/bgB_43A2.arc.LZ -x -o BGs/bgB_43A2.arc
ntcompress BGs/bgB_52AA.arc.LZ -x -o BGs/bgB_52AA.arc
ntcompress BGs/bgB_1003.arc.LZ -x -o BGs/bgB_1003.arc
ntcompress BGs/bgB_5212.arc.LZ -x -o BGs/bgB_5212.arc
ntcompress BGs/bgB_6000.arc.LZ -x -o BGs/bgB_6000.arc
ntcompress BGs/bgB_6001.arc.LZ -x -o BGs/bgB_6001.arc
ntcompress BGs/bgB_6005.arc.LZ -x -o BGs/bgB_6005.arc
ntcompress BGs/bgB_6006.arc.LZ -x -o BGs/bgB_6006.arc
ntcompress BGs/bgB_7003.arc.LZ -x -o BGs/bgB_7003.arc
ntcompress BGs/bgB_9000.arc.LZ -x -o BGs/bgB_9000.arc
ntcompress BGs/bgB_9002.arc.LZ -x -o BGs/bgB_9002.arc
ntcompress BGs/bgB_9003.arc.LZ -x -o BGs/bgB_9003.arc
ntcompress BGs/bgB_9004.arc.LZ -x -o BGs/bgB_9004.arc
ntcompress BGs/bgB_9008.arc.LZ -x -o BGs/bgB_9008.arc
ntcompress BGs/bgB_9009.arc.LZ -x -o BGs/bgB_9009.arc
ntcompress BGs/bgB_9010.arc.LZ -x -o BGs/bgB_9010.arc
ntcompress BGs/bgB_9011.arc.LZ -x -o BGs/bgB_9011.arc
ntcompress BGs/bgB_9198.arc.LZ -x -o BGs/bgB_9198.arc
ntcompress BGs/bgB_9986.arc.LZ -x -o BGs/bgB_9986.arc
ntcompress BGs/bgB_9987.arc.LZ -x -o BGs/bgB_9987.arc
ntcompress BGs/bgB_9988.arc.LZ -x -o BGs/bgB_9988.arc
ntcompress BGs/bgB_9989.arc.LZ -x -o BGs/bgB_9989.arc
ntcompress BGs/bgB_9991.arc.LZ -x -o BGs/bgB_9991.arc
ntcompress BGs/bgB_9997.arc.LZ -x -o BGs/bgB_9997.arc
ntcompress BGs/bgB_9999.arc.LZ -x -o BGs/bgB_9999.arc
ntcompress BGs/bgB_A474.arc.LZ -x -o BGs/bgB_A474.arc
ntcompress BGs/bgB_A602.arc.LZ -x -o BGs/bgB_A602.arc
ntcompress BGs/bgB_AA02.arc.LZ -x -o BGs/bgB_AA02.arc
ntcompress BGs/bgB_ABCD.arc.LZ -x -o BGs/bgB_ABCD.arc
ntcompress BGs/bgB_B00B.arc.LZ -x -o BGs/bgB_B00B.arc
ntcompress BGs/bgB_B6B2.arc.LZ -x -o BGs/bgB_B6B2.arc
ntcompress BGs/bgB_B602.arc.LZ -x -o BGs/bgB_B602.arc
ntcompress BGs/bgB_C02C.arc.LZ -x -o BGs/bgB_C02C.arc
ntcompress BGs/bgB_C02E.arc.LZ -x -o BGs/bgB_C02E.arc
ntcompress BGs/bgB_C415.arc.LZ -x -o BGs/bgB_C415.arc
ntcompress BGs/bgB_CA22.arc.LZ -x -o BGs/bgB_CA22.arc
ntcompress BGs/bgB_F1F2.arc.LZ -x -o BGs/bgB_F1F2.arc
ntcompress BGs/bgB_FAE2.arc.LZ -x -o BGs/bgB_FAE2.arc
ntcompress BGs/bgB_FAF2.arc.LZ -x -o BGs/bgB_FAF2.arc
ntcompress BGs/bgB_FCB2.arc.LZ -x -o BGs/bgB_FCB2.arc
ntcompress Maps/Bonus.kpbin.LZ -x -o Maps/Bonus.kpbin
ntcompress Maps/CrystalCaverns.kpbin.LZ -x -o  Maps/CrystalCaverns.kpbin
ntcompress Maps/Cutland.kpbin.LZ -x -o Maps/Cutland.kpbin
ntcompress Maps/Flamesinside.kpbin.LZ -x -o Maps/Flamesinside.kpbin
ntcompress Maps/Fullmap.kpbin.LZ -x -o Maps/Fullmap.kpbin
ntcompress Maps/Goldwood.kpbin.LZ -x -o Maps/Goldwood.kpbin
ntcompress Maps/KoopaPlanet.kpbin.LZ -x -o Maps/KoopaPlanet.kpbin
ntcompress Maps/KoopaPlanetUnd.kpbin.LZ -x -o Maps/KoopaPlanetUnd.kpbin
ntcompress Maps/Lava.brres.LZ -x -o Maps/Lava.brres
ntcompress Maps/Minimega.kpbin.LZ -x -o Maps/Minimega.kpbin
ntcompress Maps/MountainBackside.kpbin.LZ -x -o Maps/MountainBackside.kpbin
ntcompress Maps/Sewer.kpbin.LZ -x -o  Maps/Sewer.kpbin
ntcompress Maps/SI_Hammer.arc.LZ -x -o Maps/SI_Hammer.arc
ntcompress Maps/SkyCity.kpbin.LZ -x -o Maps/SkyCity.kpbin
ntcompress Maps/StarrySky.kpbin.LZ -x -o Maps/StarrySky.kpbin
ntcompress Maps/Water.brres.LZ -x -o Maps/Water.brres
ntcompress Maps/WSEL.kpbin.LZ -x -o Maps/WSEL.kpbin
ntcompress Maps/YoshiIsland.kpbin.LZ -x -o Maps/YoshiIsland.kpbin
ntcompress Maps/Texture/Beach.bin.LZ -x -o Maps/Texture/Beach.bin
ntcompress Maps/Texture/Beach2.bin.LZ -x -o Maps/Texture/Beach2.bin
ntcompress Maps/Texture/Beach3.bin.LZ -x -o Maps/Texture/Beach3.bin
ntcompress Maps/Texture/Beach4.bin.LZ -x -o Maps/Texture/Beach4.bin
ntcompress Maps/Texture/Beach4_RGBA8.bin.LZ -x -o Maps/Texture/Beach4_RGBA8.bin
ntcompress Maps/Texture/Beach5.bin.LZ -x -o Maps/Texture/Beach5.bin
ntcompress Maps/Texture/Bonus.bin.LZ -x -o Maps/Texture/Bonus.bin
ntcompress Maps/Texture/Cavern.bin.LZ -x -o Maps/Texture/Cavern.bin
ntcompress Maps/Texture/CavernsDark.bin.LZ -x -o Maps/Texture/CavernsDark.bin
ntcompress Maps/Texture/CRYSTALCAVE.bin.LZ -x -o Maps/Texture/CRYSTALCAVE.bin
ntcompress Maps/Texture/DARKCRYSTALCAVE.bin.LZ -x -o  Maps/Texture/DARKCRYSTALCAVE.bin
ntcompress Maps/Texture/DarkLavaGlow.bin.LZ -x -o Maps/Texture/DarkLavaGlow.bin
ntcompress Maps/Texture/Desert.bin.LZ -x -o Maps/Texture/Desert.bin
ntcompress Maps/Texture/Flagstones.bin.LZ -x -o Maps/Texture/Flagstones.bin
ntcompress Maps/Texture/Forest.bin.LZ -x -o Maps/Texture/Forest.bin
ntcompress Maps/Texture/Forest2.bin.LZ -x -o Maps/Texture/Forest2.bin
ntcompress Maps/Texture/Ghostland.bin.LZ -x -o Maps/Texture/Ghostland.bin
ntcompress Maps/Texture/Goldwood.bin.LZ -x -o Maps/Texture/Goldwood.bin
ntcompress Maps/Texture/JungleRuins.bin.LZ -x -o Maps/Texture/JungleRuins.bin
ntcompress Maps/Texture/KoopaOUT1.bin.LZ -x -o Maps/Texture/KoopaOUT1.bin
ntcompress Maps/Texture/KoopaOUT2.bin.LZ -x -o Maps/Texture/KoopaOUT2.bin
ntcompress Maps/Texture/LavaGlow.bin.LZ -x -o Maps/Texture/LavaGlow.bin
ntcompress Maps/Texture/MiniMega.bin.LZ -x -o Maps/Texture/MiniMega.bin
ntcompress Maps/Texture/MtMush.bin.LZ -x -o Maps/Texture/MtMush.bin
ntcompress Maps/Texture/NewBeach_RGBA8.bin.LZ -x -o Maps/Texture/NewBeach_RGBA8.bin
ntcompress Maps/Texture/NoharaN.bin.LZ -x -o Maps/Texture/NoharaN.bin
ntcompress Maps/Texture/Paths_W1.bin.LZ -x -o Maps/Texture/Paths_W1.bin
ntcompress Maps/Texture/Paths_W2.bin.LZ -x -o Maps/Texture/Paths_W2.bin
ntcompress Maps/Texture/Paths_W3.bin.LZ -x -o Maps/Texture/Paths_W3.bin
ntcompress Maps/Texture/Paths_W4.bin.LZ -x -o Maps/Texture/Paths_W4.bin
ntcompress Maps/Texture/Paths_W5.bin.LZ -x -o Maps/Texture/Paths_W5.bin
ntcompress Maps/Texture/Paths_W6.bin.LZ -x -o Maps/Texture/Paths_W6.bin
ntcompress Maps/Texture/Paths_W7.bin.LZ -x -o Maps/Texture/Paths_W7.bin
ntcompress Maps/Texture/Paths_W8.bin.LZ -x -o Maps/Texture/Paths_W8.bin
ntcompress Maps/Texture/Pumpkin.bin.LZ -x -o Maps/Texture/Pumpkin.bin
ntcompress Maps/Texture/PumpkinSpecial.bin.LZ -x -o Maps/Texture/PumpkinSpecial.bin
ntcompress Maps/Texture/RisingSun.bin.LZ -x -o Maps/Texture/RisingSun.bin
ntcompress Maps/Texture/Rocky.bin.LZ -x -o Maps/Texture/Rocky.bin
ntcompress Maps/Texture/Sand.bin.LZ -x -o Maps/Texture/Sand.bin
ntcompress Maps/Texture/Snowinside1.bin.LZ -x -o Maps/Texture/Snowinside1.bin
ntcompress Maps/Texture/Snowinside1_lavay.bin.LZ -x -o Maps/Texture/Snowinside1_lavay.bin
ntcompress Maps/Texture/Snowinside2.bin.LZ -x -o Maps/Texture/Snowinside2.bin
ntcompress Maps/Texture/Snowinside3.bin.LZ -x -o Maps/Texture/Snowinside3.bin
ntcompress Maps/Texture/Snowinside2_lavay.bin.LZ -x -o Maps/Texture/Snowinside2_lavay.bin
ntcompress Maps/Texture/Snowinside3_lavay.bin.LZ -x -o Maps/Texture/Snowinside3_lavay.bin
ntcompress Maps/Texture/Snowoutside.bin.LZ -x -o Maps/Texture/Snowoutside.bin
ntcompress Maps/Texture/StarHaven.bin.LZ -x -o Maps/Texture/StarHaven.bin
ntcompress Maps/Texture/StarHavenUpDown.bin.LZ -x -o Maps/Texture/StarHavenUpDown.bin
ntcompress Maps/Texture/StarRoad.bin.LZ -x -o Maps/Texture/StarRoad.bin
ntcompress Maps/Texture/uPaths_W1.bin.LZ -x -o Maps/Texture/uPaths_W1.bin
ntcompress Maps/Texture/W1Paths.bin.LZ -x -o Maps/Texture/W1Paths.bin
ntcompress "Maps/Texture/Water Edge Fullmap.bin.LZ" -x -o "Maps/Texture/Water Edge Fullmap.bin"
ntcompress Maps/Texture/Water-Edge--FF-SAK.bin.LZ -x -o Maps/Texture/Water-Edge--FF-SAK.bin
ntcompress Maps/Texture/Water-Edge--MM,-GW.bin.LZ -x -o Maps/Texture/Water-Edge--MM,-GW.bin
ntcompress Maps/Texture/Water-Edge--SW,-CC.bin.LZ -x -o Maps/Texture/Water-Edge--SW,-CC.bin
ntcompress Maps/Texture/WCCPaths.bin.LZ -x -o Maps/Texture/WCCPaths.bin
ntcompress Maps/Texture/wsele.bin.LZ -x -o Maps/Texture/wsele.bin
ntcompress SpriteTex/arrow.arc.LZ -x -o SpriteTex/arrow.arc
ntcompress SpriteTex/big_renga_block.arc.LZ -x -o SpriteTex/big_renga_block.arc
ntcompress SpriteTex/big_shell.arc.LZ -x -o SpriteTex/big_shell.arc
ntcompress SpriteTex/block_arrow.arc.LZ -x -o SpriteTex/block_arrow.arc
ntcompress SpriteTex/block_jump.arc.LZ -x -o SpriteTex/block_jump.arc
ntcompress SpriteTex/block_light.arc.LZ -x -o SpriteTex/block_light.arc
ntcompress SpriteTex/block_rotate.arc.LZ -x -o SpriteTex/block_rotate.arc
ntcompress SpriteTex/block_slide.arc.LZ -x -o SpriteTex/block_slide.arc
ntcompress SpriteTex/bombhei.arc.LZ -x -o SpriteTex/bombhei.arc
ntcompress SpriteTex/boss_koopa_lift_down.arc.LZ -x -o SpriteTex/boss_koopa_lift_down.arc
ntcompress SpriteTex/bros.arc.LZ -x -o SpriteTex/bros.arc
ntcompress SpriteTex/bubble.arc.LZ -x -o SpriteTex/bubble.arc
ntcompress SpriteTex/cage_boss_koopa.arc.LZ -x -o SpriteTex/cage_boss_koopa.arc
ntcompress SpriteTex/chestnut.arc.LZ -x -o SpriteTex/chestnut.arc
ntcompress SpriteTex/choropoo.arc.LZ -x -o SpriteTex/choropoo.arc
ntcompress SpriteTex/circle_ground.arc.LZ -x -o SpriteTex/circle_ground.arc
ntcompress SpriteTex/circle_ground_chika.arc.LZ -x -o SpriteTex/circle_ground_chika.arc
ntcompress SpriteTex/circle_ground_koopa.arc.LZ -x -o SpriteTex/circle_ground_koopa.arc
ntcompress SpriteTex/cobCourse.arc.LZ -x -o SpriteTex/cobCourse.arc
ntcompress SpriteTex/CreditsBG.arc.LZ -x -o SpriteTex/CreditsBG.arc
ntcompress SpriteTex/dossun.arc.LZ -x -o SpriteTex/dossun.arc
ntcompress SpriteTex/env_leaf.arc.LZ -x -o SpriteTex/env_leaf.arc
ntcompress SpriteTex/env_petal.arc.LZ -x -o SpriteTex/env_petal.arc
ntcompress SpriteTex/env_stardust.arc.LZ -x -o SpriteTex/env_stardust.arc
ntcompress SpriteTex/fire_cannon.arc.LZ -x -o SpriteTex/fire_cannon.arc
ntcompress SpriteTex/fruit_cookie.arc.LZ -x -o SpriteTex/fruit_cookie.arc
ntcompress SpriteTex/fruits_kusa.arc.LZ -x -o SpriteTex/fruits_kusa.arc
ntcompress SpriteTex/gabon.arc.LZ -x -o SpriteTex/gabon.arc
ntcompress SpriteTex/gabon_rock.arc.LZ -x -o SpriteTex/gabon_rock.arc
ntcompress SpriteTex/goal_set.arc.LZ -x -o SpriteTex/goal_set.arc
ntcompress SpriteTex/I_hammer.arc.LZ -x -o SpriteTex/I_hammer.arc
ntcompress SpriteTex/hammerM.arc.LZ -x -o SpriteTex/hammerM.arc
ntcompress SpriteTex/I_kinoko_bundle.arc.LZ -x -o SpriteTex/I_kinoko_bundle.arc
ntcompress SpriteTex/I_star.arc.LZ -x -o SpriteTex/I_star.arc
ntcompress SpriteTex/I_yoshi_egg.arc.LZ -x -o SpriteTex/I_yoshi_egg.arc
ntcompress SpriteTex/ibaramushi.arc.LZ -x -o SpriteTex/ibaramushi.arc
ntcompress SpriteTex/iron_ball.arc.LZ -x -o SpriteTex/iron_ball.arc
ntcompress SpriteTex/kameck_princess.arc.LZ -x -o SpriteTex/kameck_princess.arc
ntcompress SpriteTex/kanibo.arc.LZ -x -o SpriteTex/kanibo.arc
ntcompress SpriteTex/Kinopio.arc.LZ -x -o SpriteTex/Kinopio.arc
ntcompress SpriteTex/koopa.arc.LZ -x -o SpriteTex/koopa.arc
ntcompress SpriteTex/koopaJr_clown_ply.arc.LZ -x -o SpriteTex/koopaJr_clown_ply.arc
ntcompress SpriteTex/KoopaShip.arc.LZ -x -o SpriteTex/KoopaShip.arc
ntcompress SpriteTex/kuribo.arc.LZ -x -o SpriteTex/kuribo.arc
ntcompress SpriteTex/kuriboBig.arc.LZ -x -o SpriteTex/kuriboBig.arc
ntcompress SpriteTex/kuriboBoss.arc.LZ -x -o SpriteTex/kuriboBoss.arc
ntcompress SpriteTex/lakitu.arc.LZ -x -o SpriteTex/lakitu.arc
ntcompress SpriteTex/lift_buranko.arc.LZ -x -o SpriteTex/lift_buranko.arc
ntcompress SpriteTex/lift_intore.arc.LZ -x -o SpriteTex/lift_intore.arc
ntcompress SpriteTex/lift_taru.arc.LZ -x -o SpriteTex/lift_taru.arc
ntcompress SpriteTex/lift_torokko.arc.LZ -x -o SpriteTex/lift_torokko.arc
ntcompress SpriteTex/lift_trampoline.arc.LZ -x -o SpriteTex/lift_trampoline.arc
ntcompress SpriteTex/lift_yogan_kinoko.arc.LZ -x -o SpriteTex/lift_yogan_kinoko.arc
ntcompress SpriteTex/lift_zen.arc.LZ -x -o SpriteTex/lift_zen.arc
ntcompress SpriteTex/lift_zen_color_pori.arc.LZ -x -o SpriteTex/lift_zen_color_pori.arc
ntcompress SpriteTex/Luigi.arc.LZ -x -o SpriteTex/Luigi.arc
ntcompress SpriteTex/manjirou.arc.LZ -x -o SpriteTex/manjirou.arc
ntcompress SpriteTex/Mario.arc.LZ -x -o SpriteTex/Mario.arc
ntcompress SpriteTex/met.arc.LZ -x -o SpriteTex/met.arc
ntcompress SpriteTex/met_pata.arc.LZ -x -o SpriteTex/met_pata.arc
ntcompress SpriteTex/met_pataBig.arc.LZ -x -o SpriteTex/met_pataBig.arc
ntcompress SpriteTex/met_toge.arc.LZ -x -o SpriteTex/met_toge.arc
ntcompress SpriteTex/middle_flag.arc.LZ -x -o SpriteTex/middle_flag.arc
ntcompress SpriteTex/mrsun.arc.LZ -x -o SpriteTex/mrsun.arc
ntcompress SpriteTex/nokonokoA.arc.LZ -x -o SpriteTex/nokonokoA.arc
ntcompress SpriteTex/obj_coin.arc.LZ -x -o SpriteTex/obj_coin.arc
ntcompress SpriteTex/obj_Hgear.arc.LZ -x -o SpriteTex/obj_Hgear.arc
ntcompress SpriteTex/obj_kinoko.arc.LZ -x -o SpriteTex/obj_kinoko.arc
ntcompress SpriteTex/obj_turara_rakka_Big.arc.LZ -x -o SpriteTex/obj_turara_rakka_Big.arc
ntcompress SpriteTex/OpeningScene.arc.LZ -x -o SpriteTex/OpeningScene.arc
ntcompress SpriteTex/P_rcha.arc.LZ -x -o SpriteTex/P_rcha.arc
ntcompress SpriteTex/pukupuku.arc.LZ -x -o SpriteTex/pukupuku.arc
ntcompress SpriteTex/pumpkin.arc.LZ -x -o SpriteTex/pumpkin.arc
ntcompress SpriteTex/sanbo.arc.LZ -x -o SpriteTex/sanbo.arc
ntcompress SpriteTex/shyguy.arc.LZ -x -o SpriteTex/shyguy.arc
ntcompress SpriteTex/Shynja.arc.LZ -x -o SpriteTex/Shynja.arc
ntcompress SpriteTex/StarRing.arc.LZ -x -o SpriteTex/StarRing.arc
ntcompress SpriteTex/switch.arc.LZ -x -o SpriteTex/switch.arc
ntcompress SpriteTex/switch_koopa.arc.LZ -x -o SpriteTex/switch_koopa.arc
ntcompress SpriteTex/tcloud.arc.LZ -x -o SpriteTex/tcloud.arc
ntcompress SpriteTex/teresa.arc.LZ -x -o SpriteTex/teresa.arc
ntcompress SpriteTex/test_lift.arc.LZ -x -o SpriteTex/test_lift.arc
ntcompress SpriteTex/togezo.arc.LZ -x -o SpriteTex/togezo.arc
ntcompress SpriteTex/topman.arc.LZ -x -o SpriteTex/topman.arc
ntcompress SpriteTex/Y_TexGreen.arc.LZ -x -o SpriteTex/Y_TexGreen.arc
ntcompress TitleReplay/01-01_1.bin.LZ -x -o TitleReplay/01-01_1.bin
ntcompress TitleReplay/01-03_1.bin.LZ -x -o TitleReplay/01-03_1.bin
ntcompress TitleReplay/01-03_2.bin.LZ -x -o TitleReplay/01-03_2.bin
ntcompress TitleReplay/01-03_3.bin.LZ -x -o TitleReplay/01-03_3.bin
ntcompress TitleReplay/01-03_4.bin.LZ -x -o TitleReplay/01-03_4.bin
ntcompress TitleReplay/02-02_1.bin.LZ -x -o TitleReplay/02-02_1.bin
ntcompress TitleReplay/02-05_1.bin.LZ -x -o TitleReplay/02-05_1.bin
ntcompress TitleReplay/03-03_1.bin.LZ -x -o TitleReplay/03-03_1.bin
ntcompress TitleReplay/03-03_2.bin.LZ -x -o TitleReplay/03-03_2.bin
ntcompress TitleReplay/03-03_3.bin.LZ -x -o TitleReplay/03-03_3.bin
ntcompress TitleReplay/03-03_4.bin.LZ -x -o TitleReplay/03-03_4.bin
ntcompress TitleReplay/04-02_1.bin.LZ -x -o TitleReplay/04-02_1.bin
ntcompress TitleReplay/04-02_2.bin.LZ -x -o TitleReplay/04-02_2.bin
ntcompress TitleReplay/04-02_3.bin.LZ -x -o TitleReplay/04-02_3.bin
ntcompress TitleReplay/04-02_4.bin.LZ -x -o TitleReplay/04-02_4.bin
ntcompress TitleReplay/04-07_1.bin.LZ -x -o TitleReplay/04-07_1.bin
ntcompress TitleReplay/04-07_2.bin.LZ -x -o TitleReplay/04-07_2.bin
ntcompress TitleReplay/04-07_3.bin.LZ -x -o TitleReplay/04-07_3.bin
ntcompress TitleReplay/04-07_4.bin.LZ -x -o TitleReplay/04-07_4.bin
ntcompress TitleReplay/05-01_1.bin.LZ -x -o TitleReplay/05-01_1.bin
ntcompress TitleReplay/05-01_2.bin.LZ -x -o TitleReplay/05-01_2.bin
ntcompress TitleReplay/05-01_3.bin.LZ -x -o TitleReplay/05-01_3.bin
ntcompress TitleReplay/05-01_4.bin.LZ -x -o TitleReplay/05-01_4.bin
ntcompress TitleReplay/05-03_1.bin.LZ -x -o TitleReplay/05-03_1.bin
ntcompress TitleReplay/05-03_2.bin.LZ -x -o TitleReplay/05-03_2.bin
ntcompress TitleReplay/05-03_3.bin.LZ -x -o TitleReplay/05-03_3.bin
ntcompress TitleReplay/05-03_4.bin.LZ -x -o TitleReplay/05-03_4.bin
ntcompress TitleReplay/06-02_1.bin.LZ -x -o TitleReplay/06-02_1.bin
ntcompress TitleReplay/06-04_1.bin.LZ -x -o TitleReplay/06-04_1.bin
ntcompress TitleReplay/06-04_2.bin.LZ -x -o TitleReplay/06-04_2.bin
ntcompress TitleReplay/06-04_3.bin.LZ -x -o TitleReplay/06-04_3.bin
ntcompress TitleReplay/06-04_4.bin.LZ -x -o TitleReplay/06-04_4.bin
ntcompress TitleReplay/07-01_1.bin.LZ -x -o TitleReplay/07-01_1.bin
ntcompress TitleReplay/07-02_1.bin.LZ -x -o TitleReplay/07-02_1.bin
ntcompress TitleReplay/10-01_1.bin.LZ -x -o TitleReplay/10-01_1.bin
GOTO END


:END
xcopy Tilesets Stages\Texture\ /E
echo Finished Copying Tileset Files to Stages Folder
echo Finished Decompressing Newer Files. Now you're ready to use Reggie Level Editor!
pause